// ======================================================
// DATA PEMBAGIAN KAMAR MABA — PKM Imakris 2026
// ======================================================
// 'denah' = 1 gambar denah kampus yang dipakai bareng buat
// semua gedung. Taruh file gambarnya di path yang sama
// persis dengan yang ditulis di bawah (folder image/).
//
// Tiap gedung punya x/y = posisi titik (pin) huruf gedung
// itu di gambar denah, dalam PERSEN (0-100) dari kiri (x)
// & atas (y) gambar. Kalau nanti nambah gedung baru tapi
// belum tau posisinya di denah, isi x & y dengan null dulu
// — gedung itu tetap muncul & bisa dicari/diklik lewat
// daftar gedung di bawah peta, cuma belum ada pin di peta.
// ======================================================

const kamarData = {
  denah: "image/denah-kampus.jpg",
  gedung: [
    {
      id: "gedung-b-putri",
      kode: "B",
      gedung: "Gedung B",
      kategori: "Putri",
      x: 23,
      y: 76,
      kamar: [
        {
          kode: "B1",
          anggota: [
            { nama: "Kezia Kriswara Ellant Putri", fakultas: "FEB" },
            { nama: "Linggena nirigi", fakultas: "FEB" },
            { nama: "Keisha Aurelia Butar Butar", fakultas: "FMIPA" },
            { nama: "KristantI Louisiana Putri Sinaga", fakultas: "FMIPA" },
            { nama: "Vanessa Emanuella Br Ginting", fakultas: "FPSI" },
            { nama: "Puji Febrianti Br Marpaung", fakultas: "FIK" },
            { nama: "Kesya Catur Putri", fakultas: "FIP" },
            { nama: "Vebry Anisa Sinaga", fakultas: "FIS" },
            { nama: "Muncarsih Sriyati Widya Setyaningsih", fakultas: "FS" },
            { nama: "Tamariska Kristanti Pertiwi", fakultas: "FIP" },
            { nama: "Puspa Kirana", fakultas: "FIP" },
            { nama: "Electra Eve Angeline Saiya", fakultas: "FS" },
            { nama: "Adine Septia H. Tri Putri", fakultas: "FS" },
            { nama: "Gloria Paskah Pramuditha Lolo", fakultas: "FV" },
            { nama: "Grace Shila Neisha Sirait", fakultas: "FV" },
            { nama: "Kezya Aurrelia Siagian", fakultas: "FIK" },
            { nama: "Ollya Queenisha Hutabarar", fakultas: "FV" },
            { nama: "Gloria Eka Kurnia", fakultas: "FV" },
            { nama: "Gita Debora Simanjuntak", fakultas: "FV" },
            { nama: "Gescia Prilly Limbong", fakultas: "FT" },
            { nama: "Jesika Yeremia", fakultas: "FT" },
            { nama: "Yohana Tiur Maida Sianipar", fakultas: "FT" },
            { nama: "Joyce Asteria Manurung", fakultas: "FT" },
            { nama: "Yuni Lilyanita", fakultas: "FT" },
          ],
        },
        {
          kode: "B2",
          anggota: [
            { nama: "Marta Yuanita", fakultas: "FEB" },
            { nama: "Naomi Aulina Sianturi", fakultas: "FEB" },
            { nama: "Miranda Quin Oyaitouw", fakultas: "FMIPA" },
            { nama: "Naftalia Riegananda Putri", fakultas: "FMIPA" },
            { nama: "Yuclien Celsie Wahono", fakultas: "FIK" },
            { nama: "Kezya Rahel Saragih", fakultas: "FIP" },
            { nama: "Yemima Angel Giawina", fakultas: "FIS" },
            { nama: "Gabryella Koizumi Br Butarbutar", fakultas: "FT" },
            { nama: "Lilian Nainggolan", fakultas: "FS" },
            { nama: "Adeline Elvira Wadu Djawa", fakultas: "FIP" },
            { nama: "Eunike Louisa Wiranti Raharjo", fakultas: "FS" },
            { nama: "maria joceva br Sianturi", fakultas: "FIP" },
            { nama: "Venjelica Priskila Stefanny", fakultas: "FS" },
            { nama: "Shenna Adityas", fakultas: "FS" },
            { nama: "AMELLIA", fakultas: "FIK" },
            { nama: "Margaretha Angelina Nainggolan", fakultas: "FV" },
            { nama: "Natalia meylan lobang", fakultas: "FV" },
            { nama: "Grevita Ulita Batubara", fakultas: "FIK" },
            { nama: "Gultom Christine Evelyn", fakultas: "FV" },
            { nama: "Christa Caroline Vandira N", fakultas: "FV" },
            { nama: "Ribka Maria Butarbutar", fakultas: "FV" },
            { nama: "Gracia nataliana josefin suharto", fakultas: "FT" },
            { nama: "Kasih Christiana Magdalena Panjaitan", fakultas: "FT" },
            { nama: "Nathania Andrea Christine", fakultas: "FT" },
          ],
        },
        {
          kode: "B3",
          anggota: [
            { nama: "Giezti Baringbing", fakultas: "FPSI" },
            { nama: "Nindi Eka Prasetya", fakultas: "FEB" },
            { nama: "Novemby Christy", fakultas: "FEB" },
            { nama: "Neilah Haryani Zega", fakultas: "FMIPA" },
            { nama: "Reyfidela Cordelia Saragih", fakultas: "FT" },
            { nama: "Nadine Pricillia Kalalembang", fakultas: "FT" },
            { nama: "Stevia Efrianti Palinoan", fakultas: "FT" },
            { nama: "Priskila Agustina Setiani", fakultas: "FIP" },
            { nama: "Yowanda Stevany Taosu", fakultas: "FIS" },
            { nama: "Fianez Keysa Putri", fakultas: "FIP" },
            { nama: "Griselda Mirella Dianthi", fakultas: "FS" },
            { nama: "Madeline Kezia Putri Prasetyo", fakultas: "FS" },
            { nama: "EVANGELINE KEYZIANDIRA ARIZONA", fakultas: "FIP" },
            { nama: "Gamaliel Orlien Paskahlya Rieuwpassa", fakultas: "FS" },
            { nama: "Aulia Saphira Arianzah", fakultas: "FV" },
            { nama: "Karunia Bulan Krishanty", fakultas: "FIK" },
            { nama: "Ni Komang Viola Septania Adeline", fakultas: "FV" },
            { nama: "Putri Lasma Adhywidi Sinaga", fakultas: "FV" },
            { nama: "Resna Ulieklesia Siagian", fakultas: "FV" },
            { nama: "Ester Marsha Aulia", fakultas: "FV" },
          ],
        },
        {
          kode: "B4",
          anggota: [
            { nama: "Mutiara Fajaryani Lumban Tobing", fakultas: "FPSI" },
            { nama: "OLIVYA ESTER SIANTURI", fakultas: "FEB" },
            { nama: "Sesilia Armegi Putri", fakultas: "FMIPA" },
            {
              nama: "Shinta Vallery Divadillone Tannesa Sihombing",
              fakultas: "FMIPA",
            },
            { nama: "Rachel Sandy Sudarmono", fakultas: "FIP" },
            { nama: "ELBANIA TRIFENA JENIFER MALAMUK", fakultas: "FIS" },
            { nama: "Metanoia Xhezya Gunawan", fakultas: "FS" },
            { nama: "Darlene Ofel Wengkang", fakultas: "FIP" },
            { nama: "Margaretha Gita Pujiono", fakultas: "FMIPA" },
            { nama: "Chella Luize Nataly Tamtelahitu", fakultas: "FV" },
            { nama: "Cornelia Yohana Salurante", fakultas: "FIP" },
            { nama: "Erynda Intan Pratiwi", fakultas: "FV" },
          ],
        },
      ],
    },
    {
      id: "gedung-c-putri",
      kode: "C",
      gedung: "Gedung C",
      kategori: "Putri",
      x: 6,
      y: 77,
      kamar: [
        {
          kode: "C1",
          anggota: [
            { nama: "Ninda Zefanya Roulina Sidauruk", fakultas: "FPSI" },
            { nama: "Renita Haloho", fakultas: "FEB" },
            { nama: "Stella Kiara Sheelana Trixie", fakultas: "FEB" },
            { nama: "Syalomitha Angelina Nababan", fakultas: "FEB" },
            { nama: "Sidabutar Christine Flora Romauli", fakultas: "FMIPA" },
            { nama: "Siren Agustina Bangun", fakultas: "FMIPA" },
            { nama: "Renata Dwi Margaret", fakultas: "FIP" },
            { nama: "Audry jacinda parahita gunawan", fakultas: "FIS" },
            { nama: "Kezia Valerina Naomi Ndjurumana", fakultas: "FEB" },
            { nama: "Natasha Graciella Putri Efendi", fakultas: "FS" },
            { nama: "Gabriela Glory Insanian Tebisi", fakultas: "FEB" },
            { nama: "Yoana Celin Riani Siregar", fakultas: "FS" },
            { nama: "Eunike Calya Cahyaningrum", fakultas: "FIP" },
            { nama: "Meifan Renata Ester Hutabarat", fakultas: "FIS" },
            { nama: "Ribka Angela Virginia Sitompul", fakultas: "FV" },
            { nama: "Juanita Margery Rahayu", fakultas: "FIP" },
            { nama: "Sofia Rose Simaremare", fakultas: "FV" },
            { nama: "Amanda Christy", fakultas: "FEB" },
            { nama: "Abigail Karina Wardhani", fakultas: "FV" },
            { nama: "Anggieta Prizaly Narwastu Simarmata", fakultas: "FV" },
            { nama: "Esti Irin Hutabarat", fakultas: "FV" },
            { nama: "ALINE GERA SAVANA", fakultas: "FEB" },
            { nama: "Felita Carlene Annabel Candra", fakultas: "FT" },
            { nama: "Ceria Reka Julita Simanjuntak", fakultas: "FEB" },
            { nama: "Davina putri oktavia", fakultas: "FT" },
            { nama: "Dina Meytika", fakultas: "FT" },
            { nama: "Audriana Callista Putri", fakultas: "FEB" },
            { nama: "Callista Bonita Margaretha Tarigan", fakultas: "FEB" },
            { nama: "Gracella Kristiarumay Wardono", fakultas: "FIK" },
            { nama: "Sieva Nisela Putri Aliesya", fakultas: "FV" },
            { nama: "Evelyn Carolina", fakultas: "FT" },
            { nama: "Thesalonika Viona Tarigan", fakultas: "FMIPA" },
            { nama: "Ririn Andriani Rumfaker", fakultas: "FIP" },
            { nama: "Pratistha Ardyana Kristian", fakultas: "FS" },
            { nama: "Selvia Sihaloho", fakultas: "FMIPA" },
            { nama: "Artara Kasih Joselin", fakultas: "FS" },
            { nama: "FRISKILA TITANIA", fakultas: "FIK" },
            { nama: "Yvonne Antonetta Imanuella", fakultas: "FS" },
            { nama: "Aurelya Eunike Mamahit", fakultas: "FMIPA" },
            { nama: "Fiorentina Meylisa Putri Gunawan", fakultas: "FS" },
            { nama: "Stevie Nathania Dotie", fakultas: "FS" },
            { nama: "Dioxvel Sharapova Priyantoyo", fakultas: "FIS" },
            { nama: "Indah Aurelia Harianja", fakultas: "FMIPA" },
            { nama: "Keyshia Natasia Putri Surbakti", fakultas: "FMIPA" },
            { nama: "Sabelle Cherry Sunday", fakultas: "FEB" },
          ],
        },
        {
          kode: "C2",
          anggota: [
            { nama: "Kessie Agatha Beremau", fakultas: "FPSI" },
            { nama: "Tallia Joline", fakultas: "FEB" },
            { nama: "Wenny Artika Dido", fakultas: "FEB" },
            { nama: "Suluh Tianggur Siagian", fakultas: "FMIPA" },
            { nama: "Louly Loulen Sibarani", fakultas: "FT" },
            { nama: "Mey Eva Wati Tambun", fakultas: "FT" },
            { nama: "Michelle Angelique Caranay Soemariyo", fakultas: "FT" },
            { nama: "Anindya Galuh Maheswari", fakultas: "FIP" },
            { nama: "Arista Yovita Lukiningtyas", fakultas: "FS" },
            { nama: "Sheren Marselia Lumbantoruan", fakultas: "FIK" },
            { nama: "Feni Gratia Panjaitan", fakultas: "FIP" },
            { nama: "Sheila Gracia Pertiwi", fakultas: "FV" },
          ],
        },
        {
          kode: "C3",
          anggota: [
            { nama: "Angel Olivia Gustaaf", fakultas: "FPSI" },
            { nama: "Yohanna Mariany Tampubolon", fakultas: "FEB" },
            { nama: "Yesicha Stefania", fakultas: "FMIPA" },
            { nama: "Tabita Melani Nathania", fakultas: "FIP" },
            { nama: "Joyceline Kurniawan", fakultas: "FS" },
            {
              nama: "Liontin Saulina Gloria Anastasia Manullang",
              fakultas: "FIP",
            },
            { nama: "Lovely Syallome Boro", fakultas: "FPSI" },
            { nama: "Maureen Gisella Tenges Palar", fakultas: "FT" },
            { nama: "Nadia Putri Ardiyanti", fakultas: "FT" },
          ],
        },
      ],
    },
    {
      id: "gedung-g-putri",
      kode: "G",
      gedung: "Gedung G",
      kategori: "Putri",
      x: 85,
      y: 76,
      kamar: [
        {
          kode: "G1",
          anggota: [
            { nama: "Asia Syallom Elsandra Azyera", fakultas: "FMIPA" },
            { nama: "Anggreiny ertjie mamary", fakultas: "FIS" },
            { nama: "Eflyn Rara Appulembang", fakultas: "FPSI" },
            { nama: "Eugenia Faustine Punarto", fakultas: "FS" },
            { nama: "Gabriella Karunia Juliana Sianipar", fakultas: "FIK" },
            { nama: "Chrziya Alita Putri", fakultas: "FK" },
            { nama: "Cartenzya Bernadette Manurung", fakultas: "FIP" },
          ],
        },
        {
          kode: "G2",
          anggota: [
            { nama: "Audrey sharon", fakultas: "FMIPA" },
            { nama: "Asa Yustika Handadari", fakultas: "FIS" },
            { nama: "Kezzia Lareina Euodia", fakultas: "FPSI" },
            { nama: "Alva Janetta Christy Wibawa", fakultas: "FS" },
            { nama: "Fransiska E. H. Raissa Bancin", fakultas: "FT" },
            { nama: "Claudea Sefa Aprilica", fakultas: "FK" },
            { nama: "Chrizent Anariyol", fakultas: "FIP" },
          ],
        },
        {
          kode: "G3",
          anggota: [
            { nama: "CHRISTA ZANETA UMARELLA", fakultas: "FMIPA" },
            {
              nama: "Desmitha Grecya Margaret Br Siringo-ringo",
              fakultas: "FIS",
            },
            { nama: "Kasih Sola Fide", fakultas: "FIP" },
            { nama: "Natalia Elsadai Gloria", fakultas: "FIK" },
            { nama: "Elyzabeth Gita Pujiono", fakultas: "FMIPA" },
            { nama: "Cyntia aprilia", fakultas: "FK" },
            { nama: "Cynthia Rowley Hutahaean", fakultas: "FIP" },
          ],
        },
        {
          kode: "G4",
          anggota: [
            { nama: "Claudya Angel Aruan", fakultas: "FMIPA" },
            { nama: "Elbania Trifena Jenifer Malamuk", fakultas: "FIS" },
            { nama: "Vanesa Anggelisa Br Ginting", fakultas: "FS" },
            { nama: "Maria Okta Anastasya Sirait", fakultas: "FIK" },
            { nama: "Angelie Pebriana Bettin", fakultas: "FT" },
            { nama: "Ghea Ignacia", fakultas: "FK" },
            { nama: "Elyfel Ribkha Jian Cristina", fakultas: "FIP" },
          ],
        },
        {
          kode: "G5",
          anggota: [
            { nama: "Eke Margaretha Avrianti", fakultas: "FMIPA" },
            { nama: "Erzshel Naftalif Sihombing", fakultas: "FIS" },
            { nama: "Shera Octavia Tarigan", fakultas: "FS" },
            { nama: "Bunga Enggelina Nainggolan Lumbanraja", fakultas: "FIK" },
            { nama: "Yrene Joito Tamba", fakultas: "FEB" },
            { nama: "Rohana uli hutapea", fakultas: "FIMPA" },
            { nama: "Emanuela Glorya Ayu Malau", fakultas: "FIP" },
          ],
        },
        {
          kode: "G6",
          anggota: [
            { nama: "Gloria Imani Larosa", fakultas: "FIS" },
            { nama: "IRENA VITAMA SILITONGA", fakultas: "FMIPA" },
            { nama: "Daniela Raditha Sipahelut", fakultas: "FS" },
            { nama: "Vania Ozora Azalia Agatha", fakultas: "FIK" },
            { nama: "Ekklesia Sri Tiens Sihombing", fakultas: "FEB" },
            { nama: "Chellsy Nathasya Feodora Manda", fakultas: "FEB" },
            { nama: "Erina Mesyana Pasaribu", fakultas: "FIP" },
          ],
        },
        {
          kode: "G7",
          anggota: [
            { nama: "Gracia Natalie Cahyadi", fakultas: "FIS" },
            { nama: "Katherine Zefanya", fakultas: "FMIPA" },
            { nama: "Michelle Papuana Putri Mudju", fakultas: "FS" },
            { nama: "Anastasia Tirzah Ardiyanto", fakultas: "FIK" },
            { nama: "Chrissabella Lovely Michelle", fakultas: "FEB" },
            { nama: "Chris Merry Lorenza Santoso", fakultas: "FEB" },
            { nama: "Gianetta Elian Chrisanty", fakultas: "FIP" },
          ],
        },
        {
          kode: "G8",
          anggota: [
            { nama: "Jesica Anastasya Turnip", fakultas: "FIS" },
            { nama: "Kayleen Vanessa Kwee", fakultas: "FMIPA" },
            { nama: "Helena Stephine Lumban Gaol", fakultas: "FS" },
            { nama: "Ayu Abigail Sitorus", fakultas: "FIK" },
            { nama: "Christine Caecillia Sangi", fakultas: "FEB" },
            { nama: "Keyzia El Fhanio", fakultas: "FT" },
            { nama: "Gloria Kurniasakti", fakultas: "FIP" },
          ],
        },
        {
          kode: "G9",
          anggota: [
            { nama: "Elizabeth Eka Widia Putri", fakultas: "FMIPA" },
            { nama: "Elia Caroline Koosnadi", fakultas: "FT" },
            { nama: "Keisya Aurelie Faza", fakultas: "FIK" },
            { nama: "Tesyah Lenarma Sinaga", fakultas: "FPSI" },
            { nama: "Tasya Aurel Lumban Gaol", fakultas: "FIS" },
            { nama: "Graciela Atalya Saptus", fakultas: "FIP" },
            { nama: "Zefanya Bella Tampubolon", fakultas: "FS" },
          ],
        },
        {
          kode: "G10",
          anggota: [
            { nama: "Elly Sabet Tani", fakultas: "FMIPA" },
            { nama: "Risa Yuni karsi", fakultas: "FK" },
            { nama: "Sarah Crista Zefania", fakultas: "FIS" },
            { nama: "Ruth Deandra Olive Hindariadi", fakultas: "FPSI" },
            { nama: "Angelina Gita Aprilian", fakultas: "FS" },
            { nama: "Graciella Joshua Agoni", fakultas: "FIP" },
            { nama: "Karmila murib", fakultas: "FEB" },
          ],
        },
        {
          kode: "G11",
          anggota: [
            { nama: "Elysabeth Risma Simbolon", fakultas: "FMIPA" },
            { nama: "Gracella Agatha", fakultas: "FK" },
            { nama: "Ovilia Sitompul", fakultas: "FIS" },
            { nama: "YEMIMA DIAN NESTY", fakultas: "FIK" },
            { nama: "Chrisya Dona Meynanda", fakultas: "FS" },
            { nama: "Henrietta Ester Febriana", fakultas: "FIP" },
            { nama: "Jesica Audia", fakultas: "FEB" },
          ],
        },
        {
          kode: "G12",
          anggota: [
            { nama: "Firley Gracea Christy", fakultas: "FMIPA" },
            {
              nama: "NeyfaZellyne Pelangi Grace Chalystha Windy",
              fakultas: "FIS",
            },
            { nama: "Ester Morani Shaparoova BR Lumbangaol", fakultas: "FPSI" },
            { nama: "Abigail Florensia Siregar", fakultas: "FV" },
            { nama: "BRIANI ABIGAIL AWORYANE", fakultas: "FS" },
            { nama: "Herlina", fakultas: "FIP" },
            { nama: "Jenifer Oktaviah Hutahaean", fakultas: "FEB" },
          ],
        },
        {
          kode: "G13",
          anggota: [
            { nama: "Gabriela Priskila Sambao’", fakultas: "FMIPA" },
            { nama: "Nathania Wanda Reza", fakultas: "FIS" },
            { nama: "Tiara Friska Aprillia Marcony", fakultas: "FK" },
            { nama: "Alpani Nina Latersia Br Sebayang", fakultas: "FV" },
            { nama: "Kezia Aurelia Nusantara", fakultas: "FS" },
            { nama: "Irene Rambu Dupa Olihanjata", fakultas: "FIP" },
            { nama: "Heny Putri Darra", fakultas: "FEB" },
          ],
        },
        {
          kode: "G14",
          anggota: [
            { nama: "Giovanny Prasista Dewi", fakultas: "FMIPA" },
            { nama: "Natasha Imanuela Febby Dirgayasa", fakultas: "FIS" },
            { nama: "Nathania Belani Estu Setianto", fakultas: "FIK" },
            { nama: "Clara Putri Nathanella", fakultas: "FEB" },
            { nama: "Narli Nonina Mese", fakultas: "FS" },
            { nama: "Jelita Heni Ramadani Mani Huruk", fakultas: "FIP" },
            { nama: "Hana Priskila Pardede", fakultas: "FEB" },
          ],
        },
        {
          kode: "G15",
          anggota: [
            { nama: "Gracia Damai Yanti Aritonang", fakultas: "FMIPA" },
            { nama: "Fincy Suryani Silaban", fakultas: "FS" },
            { nama: "LOLITA ROHIMA PURBA", fakultas: "FIK" },
            { nama: "Ivy Ivana Yakub", fakultas: "FEB" },
            { nama: "Priska Rosalina Poppy Olua", fakultas: "FS" },
            { nama: "Jessica Aulia Anabella Marbun", fakultas: "FIP" },
            { nama: "Glinia Bolpa", fakultas: "FEB" },
          ],
        },
        {
          kode: "G16",
          anggota: [
            { nama: "Iin Marthen", fakultas: "FMIPA" },
            { nama: "Jessica Novelia Asraka", fakultas: "FIS" },
            { nama: "Novita Eliza Loida Damanik", fakultas: "FIK" },
            { nama: "Angelina Maharani", fakultas: "FV" },
            { nama: "Cherin Febrina Gultom", fakultas: "FS" },
            { nama: "Yohana Gracia Septyanti", fakultas: "FIK" },
            { nama: "Daniela Anindya Nugroho", fakultas: "FEB" },
          ],
        },
      ],
    },
    {
      id: "gedung-m2-putri",
      kode: "M2",
      gedung: "Gedung M2",
      kategori: "Putri",
      x: null,
      y: null,
      kamar: [
        {
          kode: "M2",
          anggota: [
            { nama: "Rebeca Sihite", fakultas: "FPSI" },
            {
              nama: "Veronica Falencia",
              fakultas: "FT",
              catatan: "blm konfir kalau sdh bayar",
            },
            {
              nama: "Michele Kenzo Wijaya",
              fakultas: "FS",
              catatan: "blm bayar",
            },
            { nama: "Caterina White Tubi", fakultas: "FMIPA" },
          ],
        },
      ],
    },
    {
      id: "gedung-o-putra",
      kode: "O",
      gedung: "Gedung O",
      kategori: "Putra",
      x: 73,
      y: 7,
      kamar: [
        {
          kode: "O1",
          anggota: [
            { nama: "David Christopher", fakultas: "FPSI" },
            { nama: "Daniel Nindya Priambada", fakultas: "FIS" },
            { nama: "Almen Umbu Serri", fakultas: "FT" },
            { nama: "Aldo Imanuel Wiyanto", fakultas: "FMIPA" },
            { nama: "Benaya Anasthasius Lakausu", fakultas: "FIP" },
            { nama: "Yuda Triatman Naibaho", fakultas: "FT" },
          ],
        },
        {
          kode: "O2",
          anggota: [
            { nama: "Samuel Christoper Iroth", fakultas: "FPSI" },
            { nama: "Yosua Christian Natana Prasetiyo", fakultas: "FT" },
            { nama: "Armel Samuel Imanuel Barahama", fakultas: "FT" },
            { nama: "Chrisna Wahyu Husada", fakultas: "FMIPA" },
            { nama: "Dani Setiawan Butarbutar", fakultas: "FIP" },
            { nama: "Dominus V Bayu Hutapea", fakultas: "FEB" },
          ],
        },
        {
          kode: "O3",
          anggota: [
            { nama: "David Torang Sitorus", fakultas: "FIS" },
            { nama: "Auriel Dalvaris Taruk Bua", fakultas: "FT" },
            { nama: "Gilby Christian Utomo", fakultas: "FMIPA" },
            { nama: "Hardev edyth trisnojati", fakultas: "FS" },
            { nama: "Farel Krisdianto Silaban", fakultas: "FIP" },
            { nama: "Darius Aurel Bagus Satriya", fakultas: "FEB" },
          ],
        },
        {
          kode: "O4",
          anggota: [
            { nama: "Nehemia Chika Valensia", fakultas: "FIS" },
            { nama: "Ben Gabriel Ramos Pakpahan", fakultas: "FT" },
            { nama: "Melandri Fabio Kamasi", fakultas: "FIK" },
            { nama: "Louis Alvius Budhi Prapanca", fakultas: "FIP" },
            { nama: "Jonathan Alfa Kristian Sidabutar", fakultas: "FS" },
            { nama: "Reihan Kaisna", fakultas: "FEB" },
          ],
        },
        {
          kode: "O5",
          anggota: [
            { nama: "Theo Jeremy Ginting", fakultas: "FIS" },
            { nama: "JASON RAGIL PANOGARI", fakultas: "FMIPA" },
            { nama: "Benedicto Noel Davidson", fakultas: "FT" },
            { nama: "Moses Sivan", fakultas: "FIP" },
            { nama: "Franszecha Azarya Siregar", fakultas: "FS" },
            {
              nama: "Thito Abraham Octavianus Hasoloan Sidabutar",
              fakultas: "FEB",
            },
          ],
        },
        {
          kode: "O6",
          anggota: [
            { nama: "Juan Alter Wahyudi", fakultas: "FT" },
            { nama: "Mario Raphael C E sitepu", fakultas: "FMIPA" },
            { nama: "Steven Timotius Kaito Ty", fakultas: "FK" },
            { nama: "Modesta Prima Manurung", fakultas: "FT" },
            { nama: "Jeremy Brian Christian", fakultas: "FS" },
            { nama: "Darius Denata Bagus Prasetya", fakultas: "FEB" },
          ],
        },
        {
          kode: "O7",
          anggota: [
            { nama: "Vincent Adrian Nababan", fakultas: "FMIPA" },
            { nama: "Jonathan Valetino Bauda", fakultas: "FT" },
            { nama: "Adriel Joshephino Noriega", fakultas: "FV" },
            { nama: "Pierce Exchaudio Purba", fakultas: "FT" },
            { nama: "Jose Axel Cahyono", fakultas: "FS" },
            { nama: "Andika Bintang Putra Pratama", fakultas: "FEB" },
          ],
        },
        {
          kode: "O8",
          anggota: [
            { nama: "Elnath Tegar Prawiro Yudho", fakultas: "FMIPA" },
            { nama: "Reivanio Immanuel Etanim", fakultas: "FIK" },
            { nama: "Austin Azarel", fakultas: "FV" },
            { nama: "Rafhael Lamba Padang", fakultas: "FT" },
            { nama: "Jocelin Crystian Wiratama", fakultas: "FS" },
            { nama: "Abner Zanuard Tambunan", fakultas: "FEB" },
          ],
        },
        {
          kode: "O9",
          anggota: [
            { nama: "Bryant Prawiranta Perangin Angin", fakultas: "FMIPA" },
            { nama: "Siong Fah Cin", fakultas: "FIK" },
            { nama: "David Raul Kenzo Napitupulu", fakultas: "FV" },
            { nama: "Raphael Michael Hiu", fakultas: "FT" },
            { nama: "Dickna Adi Cassatrya", fakultas: "FS" },
            { nama: "Yosua Christian Wiratama", fakultas: "FEB" },
          ],
        },
        {
          kode: "O10",
          anggota: [
            { nama: "Gift Theo Valentino", fakultas: "FV" },
            { nama: "Pieter Efesus", fakultas: "FEB" },
            { nama: "Steven Dwight Sugito", fakultas: "FT" },
            { nama: "Samuel Steven Manalu", fakultas: "FT" },
            { nama: "Yulio Abramando", fakultas: "FS" },
            { nama: "Gosyen Gabriel M. Simanjuntak", fakultas: "FEB" },
          ],
        },
        {
          kode: "O11",
          anggota: [
            { nama: "Benhard Alexander Sirait", fakultas: "FMIPA" },
            { nama: "Nathaniel Ruby", fakultas: "FIK" },
            { nama: "Darius Denanda Bagus Prasetya", fakultas: "FIS" },
            { nama: "Edward Imanuel", fakultas: "FT" },
            { nama: "Ray Renaldi Sitorus", fakultas: "FEB" },
            { nama: "Mikhaelo Christoper Benecdiastha", fakultas: "FMIPA" },
          ],
        },
        {
          kode: "O12",
          anggota: [
            { nama: "Galvin Renardo Layang", fakultas: "FMIPA" },
            { nama: "Nommensen Wiratama Ambarita", fakultas: "FIK" },
            { nama: "Josepin Siahaan", fakultas: "FV" },
            { nama: "Emmanuel Calipsias Christoparela Emenk", fakultas: "FV" },
            { nama: "James Filippus Napitupulu", fakultas: "FT" },
            { nama: "Edith Christo Saragih", fakultas: "FV" },
          ],
        },
        {
          kode: "O13",
          anggota: [
            { nama: "Glend Alinski Natanael", fakultas: "FMIPA" },
            { nama: "Yoses Emmanuel Baptize", fakultas: "FIK" },
            { nama: "Avram Tetandho Gumilang Kasim", fakultas: "FV" },
            { nama: "Joan Pangarawahenu", fakultas: "FT" },
            { nama: "Jonathan Iskandar", fakultas: "FEB" },
            {
              nama: "Ricki Ronal Maas",
              fakultas: "FEB",
              catatan: "belum bayar, belum daftar",
            },
          ],
        },
        {
          kode: "O14",
          anggota: [
            { nama: "Hizkia Syalom Setyadi", fakultas: "FMIPA" },
            {
              nama: "Eleazar Ajaib Sihdapma Putra Beya Gaharu",
              fakultas: "FIK",
            },
            { nama: "Mike Douglas Simangunsong", fakultas: "FT" },
            { nama: "Vionell firstian Nixon febi elycio", fakultas: "FV" },
            { nama: "Shintong Vernanditho Pakpahan", fakultas: "FT" },
          ],
        },
        {
          kode: "O15",
          anggota: [
            { nama: "Jonathan Shallom Cellose", fakultas: "FMIPA" },
            { nama: "Rius Simon", fakultas: "FIK" },
            { nama: "Sam Peter Zhong", fakultas: "FV" },
            { nama: "Exsel Nathanael", fakultas: "FT" },
            { nama: "zeppelyn amadheo yuanta", fakultas: "FT" },
            { nama: "Leo Candrika Lucy Prabasa", fakultas: "FIK" },
          ],
        },
        {
          kode: "O16",
          anggota: [
            { nama: "NIMROD KRISTIANO SIHOMBING", fakultas: "FMIPA" },
            { nama: "Christian Sutanto", fakultas: "FIK" },
            { nama: "Reynaldi saputra sianturi", fakultas: "FV" },
            { nama: "Given march Ramschie", fakultas: "FT" },
            { nama: "Abraham Sigra Marcelino Tampubolon", fakultas: "FEB" },
          ],
        },
        {
          kode: "O17",
          anggota: [
            { nama: "Vebriel Maha Putra Ziliwu", fakultas: "FMIPA" },
            { nama: "Farel Cristian Patulak", fakultas: "FIK" },
            { nama: "Reyhan Siregar", fakultas: "FV" },
            { nama: "Tohap Manalu", fakultas: "FT" },
            { nama: "Glenn Marcello Krisna Anang Kusuma", fakultas: "FS" },
          ],
        },
        {
          kode: "O18",
          anggota: [
            { nama: "Frendi Sipayung", fakultas: "FMIPA" },
            { nama: "Lambang Putra Pamungkas", fakultas: "FV" },
            { nama: "Timothy Aurelio", fakultas: "FT" },
            { nama: "Tobias ade ramonsyah saragih", fakultas: "FT" },
            { nama: "Paulus Jordan", fakultas: "FEB" },
          ],
        },
        {
          kode: "O19",
          anggota: [
            { nama: "Joshua Orvin", fakultas: "FV" },
            { nama: "Steven Novrianto Arpin", fakultas: "FT" },
            { nama: "Stevie Salomo Titaley", fakultas: "FT" },
            { nama: "Christian Manuela Javaz", fakultas: "FEB" },
            { nama: "Bryan Orlando Natty", fakultas: "FT" },
          ],
        },
        {
          kode: "O20",
          anggota: [
            { nama: "Yehezkiel Fabian Permana Setjo", fakultas: "FS" },
            { nama: "Glenn Jeconia Jerikho", fakultas: "FV" },
            { nama: "Filifi Generald Aprilius", fakultas: "FT" },
            { nama: "Markus Adi Hermanto", fakultas: "FT" },
            { nama: "Moses Andrean Syeba", fakultas: "FEB" },
          ],
        },
        {
          kode: "O21",
          anggota: [
            { nama: "Jovande Samadi", fakultas: "FT" },
            { nama: "Christian Lufen Bahara Adi Legowo", fakultas: "FT" },
            { nama: "Hosea H Simatupang", fakultas: "FMIPA" },
            { nama: "Eldith Christo Saragih", fakultas: "FV" },
          ],
        },
        {
          kode: "O22",
          anggota: [
            { nama: "Made Elnathan A.G", fakultas: "FT" },
            { nama: "Samuel Kenneth Jocelan", fakultas: "FV" },
            { nama: "Novrianus Jastin T. Lolu", fakultas: "FK" },
            { nama: "Jeremia Ndru Pangihutan Sianturi", fakultas: "FEB" },
            { nama: "Kevin Volcker Hutajulu", fakultas: "FIS" },
            { nama: "Yoshua Oktavio", fakultas: "FT" },
          ],
        },
        {
          kode: "O23",
          anggota: [
            { nama: "Alfreda Vicky Prima Wijaya", fakultas: "FIK" },
            { nama: "Betuel Kevin Seo", fakultas: "FEB" },
            { nama: "Evan Galen Prissyandi", fakultas: "FT" },
            { nama: "Ubat Cristian Siagian", fakultas: "FEB" },
            { nama: "Fires Arka Wisesa", fakultas: "FV" },
            { nama: "Yoel Yesnath", fakultas: "FIK" },
          ],
        },
      ],
    },
  ],
};

export default kamarData;
