const kelompokMaba = [
  {
    nama: "ABEDNEGO LUDWIAN WICAKSONO",
    fakultas: "FIS",
    noKel: "1",
    namaKelompok: "Kristal",
    kakakKelompok: "Andhara",
    kakakPI: "Ruth Natasya",
  },
  {
    nama: "VIONA OHOIRAT",
    fakultas: "FIS",
    noKel: "1",
    namaKelompok: "Kristal",
    kakakKelompok: "Andhara",
    kakakPI: "Ruth Natasya",
  },
  {
    nama: "ANGEL OLIVIA GUSTAAF",
    fakultas: "FPSI",
    noKel: "1",
    namaKelompok: "Kristal",
    kakakKelompok: "Andhara",
    kakakPI: "Ruth Natasya",
  },
  {
    nama: "PAULUS JORDAN",
    fakultas: "FEB",
    noKel: "1",
    namaKelompok: "Kristal",
    kakakKelompok: "Andhara",
    kakakPI: "Ruth Natasya",
  },
  {
    nama: "TALLIA JOLINE",
    fakultas: "FEB",
    noKel: "1",
    namaKelompok: "Kristal",
    kakakKelompok: "Andhara",
    kakakPI: "Ruth Natasya",
  },
  {
    nama: "MELANDRI FABIO KAMASINA",
    fakultas: "FIK",
    noKel: "1",
    namaKelompok: "Kristal",
    kakakKelompok: "Andhara",
    kakakPI: "Ruth Natasya",
  },
  {
    nama: "ALMEN UMBU SERRI",
    fakultas: "FT",
    noKel: "1",
    namaKelompok: "Kristal",
    kakakKelompok: "Andhara",
    kakakPI: "Ruth Natasya",
  },
  {
    nama: "ALDO IMANUEL WIYANTO",
    fakultas: "FMIPA",
    noKel: "1",
    namaKelompok: "Kristal",
    kakakKelompok: "Andhara",
    kakakPI: "Ruth Natasya",
  },
  {
    nama: "ALFADRA SETIA WAHYUNINGTYAS",
    fakultas: "FMIPA",
    noKel: "1",
    namaKelompok: "Kristal",
    kakakKelompok: "Andhara",
    kakakPI: "Ruth Natasya",
  },
  {
    nama: "ANGELIE PEBRIANA BETTIN",
    fakultas: "FT",
    noKel: "1",
    namaKelompok: "Kristal",
    kakakKelompok: "Andhara",
    kakakPI: "Ruth Natasya",
  },
  {
    nama: "HELENA STEPHINE LUMBAN GAOL",
    fakultas: "FS",
    noKel: "1",
    namaKelompok: "Kristal",
    kakakKelompok: "Andhara",
    kakakPI: "Ruth Natasya",
  },
  {
    nama: "STEVEN NOVRIANTO ARPIN",
    fakultas: "FT",
    noKel: "1",
    namaKelompok: "Kristal",
    kakakKelompok: "Andhara",
    kakakPI: "Ruth Natasya",
  },
  {
    nama: "CYNTHIA ALISPA BR. PARDOSI",
    fakultas: "FPSI",
    noKel: "2",
    namaKelompok: "Aurora",
    kakakKelompok: "Widel",
    kakakPI: "Andrea",
  },
  {
    nama: "ALVERDO SITUMORANG",
    fakultas: "FIS",
    noKel: "2",
    namaKelompok: "Aurora",
    kakakKelompok: "Widel",
    kakakPI: "Andrea",
  },
  {
    nama: "TASYA AUREL LUMBAN GAOL",
    fakultas: "FIS",
    noKel: "2",
    namaKelompok: "Aurora",
    kakakKelompok: "Widel",
    kakakPI: "Andrea",
  },
  {
    nama: "DARIUS DENATA BAGUS PRASETYA",
    fakultas: "FEB",
    noKel: "2",
    namaKelompok: "Aurora",
    kakakKelompok: "Widel",
    kakakPI: "Andrea",
  },
  {
    nama: "KARMILA MURIB",
    fakultas: "FEB",
    noKel: "2",
    namaKelompok: "Aurora",
    kakakKelompok: "Widel",
    kakakPI: "Andrea",
  },
  {
    nama: "ARMEL SAMUEL IMANUEL BARAHAMA",
    fakultas: "FT",
    noKel: "2",
    namaKelompok: "Aurora",
    kakakKelompok: "Widel",
    kakakPI: "Andrea",
  },
  {
    nama: "ASIA SYALLOM ELSANDRA AZYERA",
    fakultas: "FMIPA",
    noKel: "2",
    namaKelompok: "Aurora",
    kakakKelompok: "Widel",
    kakakPI: "Andrea",
  },
  {
    nama: "ANINDIO RAFAEL CHRIS PUTRA",
    fakultas: "FMIPA",
    noKel: "2",
    namaKelompok: "Aurora",
    kakakKelompok: "Widel",
    kakakPI: "Andrea",
  },
  {
    nama: "DAVINA PUTRI OKTAVIA",
    fakultas: "FT",
    noKel: "2",
    namaKelompok: "Aurora",
    kakakKelompok: "Widel",
    kakakPI: "Andrea",
  },
  {
    nama: "RAFAEL MARCO OBRIANT",
    fakultas: "FS",
    noKel: "2",
    namaKelompok: "Aurora",
    kakakKelompok: "Widel",
    kakakPI: "Andrea",
  },
  {
    nama: "STEVEN TIMOTIUS KAITO TY",
    fakultas: "FK",
    noKel: "2",
    namaKelompok: "Aurora",
    kakakKelompok: "Widel",
    kakakPI: "Andrea",
  },
  {
    nama: "EFLYN RARA APPULEMBANG",
    fakultas: "FPSI",
    noKel: "3",
    namaKelompok: "Embun",
    kakakKelompok: "Darryl",
    kakakPI: "Ines",
  },
  {
    nama: "AMOS PALANGKA RANAN",
    fakultas: "FIS",
    noKel: "3",
    namaKelompok: "Embun",
    kakakKelompok: "Darryl",
    kakakPI: "Ines",
  },
  {
    nama: "GLORIA IMANI LAROSA",
    fakultas: "FIS",
    noKel: "3",
    namaKelompok: "Embun",
    kakakKelompok: "Darryl",
    kakakPI: "Ines",
  },
  {
    nama: "JOEL PANJAITAN",
    fakultas: "FEB",
    noKel: "3",
    namaKelompok: "Embun",
    kakakKelompok: "Darryl",
    kakakPI: "Ines",
  },
  {
    nama: "KEZIA KRISWARA ELLANT PUTRI",
    fakultas: "FEB",
    noKel: "3",
    namaKelompok: "Embun",
    kakakKelompok: "Darryl",
    kakakPI: "Ines",
  },
  {
    nama: "AURIEL DALVARIS TARUK BUA",
    fakultas: "FT",
    noKel: "3",
    namaKelompok: "Embun",
    kakakKelompok: "Darryl",
    kakakPI: "Ines",
  },
  {
    nama: "DINA MEYTIKA",
    fakultas: "FT",
    noKel: "3",
    namaKelompok: "Embun",
    kakakKelompok: "Darryl",
    kakakPI: "Ines",
  },
  {
    nama: "AUDREY SHARON",
    fakultas: "FMIPA",
    noKel: "3",
    namaKelompok: "Embun",
    kakakKelompok: "Darryl",
    kakakPI: "Ines",
  },
  {
    nama: "BENHARD ALEXANDER SIRAIT",
    fakultas: "FMIPA",
    noKel: "3",
    namaKelompok: "Embun",
    kakakKelompok: "Darryl",
    kakakPI: "Ines",
  },
  {
    nama: "TIARA FRISKA APRILLIA MARCONY",
    fakultas: "FK",
    noKel: "3",
    namaKelompok: "Embun",
    kakakKelompok: "Darryl",
    kakakPI: "Ines",
  },
  {
    nama: "JONATHAN ALFA KRISTIAN SIDABUTAR",
    fakultas: "FS",
    noKel: "3",
    namaKelompok: "Embun",
    kakakKelompok: "Darryl",
    kakakPI: "Ines",
  },
  {
    nama: "ESTER MORANI SHAPAROOVA LUMBANGAOL",
    fakultas: "FPSI",
    noKel: "4",
    namaKelompok: "Penguin",
    kakakKelompok: "Lilis",
    kakakPI: "Jean Merry",
  },
  {
    nama: "MARION GIRANG HERMANTO",
    fakultas: "FIS",
    noKel: "4",
    namaKelompok: "Penguin",
    kakakKelompok: "Lilis",
    kakakPI: "Jean Merry",
  },
  {
    nama: "DOMINUS V BAYU HUTAPEA",
    fakultas: "FEB",
    noKel: "4",
    namaKelompok: "Penguin",
    kakakKelompok: "Lilis",
    kakakPI: "Jean Merry",
  },
  {
    nama: "CHRIS MERRY LORENZA SANTOSO",
    fakultas: "FEB",
    noKel: "4",
    namaKelompok: "Penguin",
    kakakKelompok: "Lilis",
    kakakPI: "Jean Merry",
  },
  {
    nama: "AURELYA EUNIKE MAMAHIT",
    fakultas: "FMIPA",
    noKel: "4",
    namaKelompok: "Penguin",
    kakakKelompok: "Lilis",
    kakakPI: "Jean Merry",
  },
  {
    nama: "BEN GABRIEL RAMOS PAKPAHAN",
    fakultas: "FT",
    noKel: "4",
    namaKelompok: "Penguin",
    kakakKelompok: "Lilis",
    kakakPI: "Jean Merry",
  },
  {
    nama: "ELIA CAROLINE KOOSNADI",
    fakultas: "FT",
    noKel: "4",
    namaKelompok: "Penguin",
    kakakKelompok: "Lilis",
    kakakPI: "Jean Merry",
  },
  {
    nama: "LOLITA ROHIMA PURBA",
    fakultas: "FIK",
    noKel: "4",
    namaKelompok: "Penguin",
    kakakKelompok: "Lilis",
    kakakPI: "Jean Merry",
  },
  {
    nama: "RUTH DELINA VANECIA PANG",
    fakultas: "FS",
    noKel: "4",
    namaKelompok: "Penguin",
    kakakKelompok: "Lilis",
    kakakPI: "Jean Merry",
  },
  {
    nama: "SAM PETER ZHONF",
    fakultas: "FV",
    noKel: "4",
    namaKelompok: "Penguin",
    kakakKelompok: "Lilis",
    kakakPI: "Jean Merry",
  },
  {
    nama: "CHRISTIAN SUTANTO",
    fakultas: "FIK",
    noKel: "4",
    namaKelompok: "Penguin",
    kakakKelompok: "Lilis",
    kakakPI: "Jean Merry",
  },
  {
    nama: "GIEZTI BARINGBING",
    fakultas: "FPSI",
    noKel: "5",
    namaKelompok: "Rusa",
    kakakKelompok: "Adel",
    kakakPI: "Destya",
  },
  {
    nama: "NATASHA IMANUELA FEBBY DIRGAYASA",
    fakultas: "FIS",
    noKel: "5",
    namaKelompok: "Rusa",
    kakakKelompok: "Adel",
    kakakPI: "Destya",
  },
  {
    nama: "JOSHUA IMANUEL FELIKS",
    fakultas: "FEB",
    noKel: "5",
    namaKelompok: "Rusa",
    kakakKelompok: "Adel",
    kakakPI: "Destya",
  },
  {
    nama: "WENNY ARTIKA DIDO",
    fakultas: "FEB",
    noKel: "5",
    namaKelompok: "Rusa",
    kakakKelompok: "Adel",
    kakakPI: "Destya",
  },
  {
    nama: "CATERINA WHITE TUBI",
    fakultas: "FMIPA",
    noKel: "5",
    namaKelompok: "Rusa",
    kakakKelompok: "Adel",
    kakakPI: "Destya",
  },
  {
    nama: "BENEDICTO NOEL DAVIDSON",
    fakultas: "FT",
    noKel: "5",
    namaKelompok: "Rusa",
    kakakKelompok: "Adel",
    kakakPI: "Destya",
  },
  {
    nama: "EVELYN CAROLINA",
    fakultas: "FT",
    noKel: "5",
    namaKelompok: "Rusa",
    kakakKelompok: "Adel",
    kakakPI: "Destya",
  },
  {
    nama: "YUCLIEN CELSIE WAHONO",
    fakultas: "FIK",
    noKel: "5",
    namaKelompok: "Rusa",
    kakakKelompok: "Adel",
    kakakPI: "Destya",
  },
  {
    nama: "REYVANDO DIMAS PRATYA",
    fakultas: "FS",
    noKel: "5",
    namaKelompok: "Rusa",
    kakakKelompok: "Adel",
    kakakPI: "Destya",
  },
  {
    nama: "SAMUEL KENNETH JOCELAN",
    fakultas: "FV",
    noKel: "5",
    namaKelompok: "Rusa",
    kakakKelompok: "Adel",
    kakakPI: "Destya",
  },
  {
    nama: "CARTENZYA BERNADETTE MANURUNG",
    fakultas: "FIP",
    noKel: "5",
    namaKelompok: "Rusa",
    kakakKelompok: "Adel",
    kakakPI: "Destya",
  },
  {
    nama: "GISELLA CELINE TIORO PANJAITAN",
    fakultas: "FPSI",
    noKel: "6",
    namaKelompok: "Rubah",
    kakakKelompok: "Farel Aldhepo",
    kakakPI: "Frigia",
  },
  {
    nama: "MARSHALL MARVELLOUS CHRISTIAN JULIAN",
    fakultas: "FIS",
    noKel: "6",
    namaKelompok: "Rubah",
    kakakKelompok: "Farel Aldhepo",
    kakakPI: "Frigia",
  },
  {
    nama: "JECK DANIEL MAYCLINTON SARAGIH",
    fakultas: "FEB",
    noKel: "6",
    namaKelompok: "Rubah",
    kakakKelompok: "Farel Aldhepo",
    kakakPI: "Frigia",
  },
  {
    nama: "CALLISTA BONITA MARGARETHA TARIGAN",
    fakultas: "FEB",
    noKel: "6",
    namaKelompok: "Rubah",
    kakakKelompok: "Farel Aldhepo",
    kakakPI: "Frigia",
  },
  {
    nama: "CHARISSA GILDA SUBAGIO",
    fakultas: "FMIPA",
    noKel: "6",
    namaKelompok: "Rubah",
    kakakKelompok: "Farel Aldhepo",
    kakakPI: "Frigia",
  },
  {
    nama: "ADRIEL JOSHEPHINO NORIEGA",
    fakultas: "FV",
    noKel: "6",
    namaKelompok: "Rubah",
    kakakKelompok: "Farel Aldhepo",
    kakakPI: "Frigia",
  },
  {
    nama: "BRYAN ORLANDO NATTY",
    fakultas: "FT",
    noKel: "6",
    namaKelompok: "Rubah",
    kakakKelompok: "Farel Aldhepo",
    kakakPI: "Frigia",
  },
  {
    nama: "FERLITA CARLENE ANNABEL CANDRA",
    fakultas: "FT",
    noKel: "6",
    namaKelompok: "Rubah",
    kakakKelompok: "Farel Aldhepo",
    kakakPI: "Frigia",
  },
  {
    nama: "MARIA OKTA ANASTASYA SIRAIT",
    fakultas: "FIK",
    noKel: "6",
    namaKelompok: "Rubah",
    kakakKelompok: "Farel Aldhepo",
    kakakPI: "Frigia",
  },
  {
    nama: "FIORENTINA MEYLISA PUTRI GUNAWAN",
    fakultas: "FS",
    noKel: "6",
    namaKelompok: "Rubah",
    kakakKelompok: "Farel Aldhepo",
    kakakPI: "Frigia",
  },
  {
    nama: "SHEILA GRACIA PERTIWI",
    fakultas: "FV",
    noKel: "6",
    namaKelompok: "Rubah",
    kakakKelompok: "Farel Aldhepo",
    kakakPI: "Frigia",
  },
  {
    nama: "YEMIMA ANGEL GIAWINA",
    fakultas: "FIS",
    noKel: "7",
    namaKelompok: "Beruang",
    kakakKelompok: "Volgentino",
    kakakPI: "Abigail Rizya",
  },
  {
    nama: "GIDEON WICAKSONO",
    fakultas: "FEB",
    noKel: "7",
    namaKelompok: "Beruang",
    kakakKelompok: "Volgentino",
    kakakPI: "Abigail Rizya",
  },
  {
    nama: "DANIELA ANINDYA NUGROHO",
    fakultas: "FEB",
    noKel: "7",
    namaKelompok: "Beruang",
    kakakKelompok: "Volgentino",
    kakakPI: "Abigail Rizya",
  },
  {
    nama: "CHRISTA ZANETA UMARELLA",
    fakultas: "FMIPA",
    noKel: "7",
    namaKelompok: "Beruang",
    kakakKelompok: "Volgentino",
    kakakPI: "Abigail Rizya",
  },
  {
    nama: "ABIGAIL FLORENSIA",
    fakultas: "FV",
    noKel: "7",
    namaKelompok: "Beruang",
    kakakKelompok: "Volgentino",
    kakakPI: "Abigail Rizya",
  },
  {
    nama: "EDWARD IMANUEL",
    fakultas: "FT",
    noKel: "7",
    namaKelompok: "Beruang",
    kakakKelompok: "Volgentino",
    kakakPI: "Abigail Rizya",
  },
  {
    nama: "YOEL YESNATH",
    fakultas: "FIK",
    noKel: "7",
    namaKelompok: "Beruang",
    kakakKelompok: "Volgentino",
    kakakPI: "Abigail Rizya",
  },
  {
    nama: "SHINTA EKAMANUELA PUTRIARIYUWANTO",
    fakultas: "FV",
    noKel: "7",
    namaKelompok: "Beruang",
    kakakKelompok: "Volgentino",
    kakakPI: "Abigail Rizya",
  },
  {
    nama: "NIRA ORYSA SATIVA",
    fakultas: "FS",
    noKel: "7",
    namaKelompok: "Beruang",
    kakakKelompok: "Volgentino",
    kakakPI: "Abigail Rizya",
  },
  {
    nama: "SOFIA ROSE SIMAREMARE",
    fakultas: "FV",
    noKel: "7",
    namaKelompok: "Beruang",
    kakakKelompok: "Volgentino",
    kakakPI: "Abigail Rizya",
  },
  {
    nama: "CHRIZENT ANARIYOL",
    fakultas: "FIP",
    noKel: "7",
    namaKelompok: "Beruang",
    kakakKelompok: "Volgentino",
    kakakPI: "Abigail Rizya",
  },
  {
    nama: "NATANIEL VERDIANTO",
    fakultas: "FIS",
    noKel: "8",
    namaKelompok: "Serigala",
    kakakKelompok: "Gaby",
    kakakPI: "Jovan Holly",
  },
  {
    nama: "GLINIA BOLPA",
    fakultas: "FEB",
    noKel: "8",
    namaKelompok: "Serigala",
    kakakKelompok: "Gaby",
    kakakPI: "Jovan Holly",
  },
  {
    nama: "CLAUDYA ANGEL ARUAN",
    fakultas: "FMIPA",
    noKel: "8",
    namaKelompok: "Serigala",
    kakakKelompok: "Gaby",
    kakakPI: "Jovan Holly",
  },
  {
    nama: "AGASTHYA VIKESHA",
    fakultas: "FV",
    noKel: "8",
    namaKelompok: "Serigala",
    kakakKelompok: "Gaby",
    kakakPI: "Jovan Holly",
  },
  {
    nama: "EVAN GALEN PRISSYANDI",
    fakultas: "FT",
    noKel: "8",
    namaKelompok: "Serigala",
    kakakKelompok: "Gaby",
    kakakPI: "Jovan Holly",
  },
  {
    nama: "YURIKA THRESIA CHRISTIANI",
    fakultas: "FK",
    noKel: "8",
    namaKelompok: "Serigala",
    kakakKelompok: "Gaby",
    kakakPI: "Jovan Holly",
  },
  {
    nama: "GIDEON JOSEPH WIYANA",
    fakultas: "FIK",
    noKel: "8",
    namaKelompok: "Serigala",
    kakakKelompok: "Gaby",
    kakakPI: "Jovan Holly",
  },
  {
    nama: "SIEVA NISELA PUTRI ALIESYA",
    fakultas: "FV",
    noKel: "8",
    namaKelompok: "Serigala",
    kakakKelompok: "Gaby",
    kakakPI: "Jovan Holly",
  },
  {
    nama: "PUTU RATIH MAHARANI SUWARSO",
    fakultas: "FS",
    noKel: "8",
    namaKelompok: "Serigala",
    kakakKelompok: "Gaby",
    kakakPI: "Jovan Holly",
  },
  {
    nama: "CHYNTIA MEILIANA DENITA SARI",
    fakultas: "FIP",
    noKel: "8",
    namaKelompok: "Serigala",
    kakakKelompok: "Gaby",
    kakakPI: "Jovan Holly",
  },
  {
    nama: "RIRIN ANDRIANI RUMFAKER",
    fakultas: "FIP",
    noKel: "8",
    namaKelompok: "Serigala",
    kakakKelompok: "Gaby",
    kakakPI: "Jovan Holly",
  },
  {
    nama: "NEHEMIA CHIKA VALENSIA",
    fakultas: "FIS",
    noKel: "9",
    namaKelompok: "Kelinci",
    kakakKelompok: "Shelby",
    kakakPI: "Adryan Nathanael",
  },
  {
    nama: "MADRID PELLETIMU",
    fakultas: "FEB",
    noKel: "9",
    namaKelompok: "Kelinci",
    kakakKelompok: "Shelby",
    kakakPI: "Adryan Nathanael",
  },
  {
    nama: "OLIVYA ESTER SIANTURI",
    fakultas: "FEB",
    noKel: "9",
    namaKelompok: "Kelinci",
    kakakKelompok: "Shelby",
    kakakPI: "Adryan Nathanael",
  },
  {
    nama: "EKE MARGARETHA AVRIANTI",
    fakultas: "FMIPA",
    noKel: "9",
    namaKelompok: "Kelinci",
    kakakKelompok: "Shelby",
    kakakPI: "Adryan Nathanael",
  },
  {
    nama: "ABIGAIL KARINA WARDHANI",
    fakultas: "FV",
    noKel: "9",
    namaKelompok: "Kelinci",
    kakakKelompok: "Shelby",
    kakakPI: "Adryan Nathanael",
  },
  {
    nama: "EXSEL NATHANAEL",
    fakultas: "FT",
    noKel: "9",
    namaKelompok: "Kelinci",
    kakakKelompok: "Shelby",
    kakakPI: "Adryan Nathanael",
  },
  {
    nama: "ARDO ARDIAN PRADANA",
    fakultas: "FIK",
    noKel: "9",
    namaKelompok: "Kelinci",
    kakakKelompok: "Shelby",
    kakakPI: "Adryan Nathanael",
  },
  {
    nama: "VERNANDI NEO SAPUTRA",
    fakultas: "FV",
    noKel: "9",
    namaKelompok: "Kelinci",
    kakakKelompok: "Shelby",
    kakakPI: "Adryan Nathanael",
  },
  {
    nama: "MADELINE KEZIA PUTRI PRASETYO",
    fakultas: "FS",
    noKel: "9",
    namaKelompok: "Kelinci",
    kakakKelompok: "Shelby",
    kakakPI: "Adryan Nathanael",
  },
  {
    nama: "CORNELIA YOHANA VERONIKA SALURANTE",
    fakultas: "FIP",
    noKel: "9",
    namaKelompok: "Kelinci",
    kakakKelompok: "Shelby",
    kakakPI: "Adryan Nathanael",
  },
  {
    nama: "SHINTONG VERNANDITHO PAKPAHAN",
    fakultas: "FT",
    noKel: "9",
    namaKelompok: "Kelinci",
    kakakKelompok: "Shelby",
    kakakPI: "Adryan Nathanael",
  },
  {
    nama: "PANGERAN TIMOTHY PERDANA SIMANJUNTAK",
    fakultas: "FIS",
    noKel: "10",
    namaKelompok: "Santa",
    kakakKelompok: "Natan",
    kakakPI: "Debi Fanessa",
  },
  {
    nama: "JEREMIA NDRU PANGIHUTAN SIANTURI",
    fakultas: "FEB",
    noKel: "10",
    namaKelompok: "Santa",
    kakakKelompok: "Natan",
    kakakPI: "Debi Fanessa",
  },
  {
    nama: "LINGGENA NIRIGI",
    fakultas: "FEB",
    noKel: "10",
    namaKelompok: "Santa",
    kakakKelompok: "Natan",
    kakakPI: "Debi Fanessa",
  },
  {
    nama: "ELIZABETH EKA WIDIA PUTRI",
    fakultas: "FMIPA",
    noKel: "10",
    namaKelompok: "Santa",
    kakakKelompok: "Natan",
    kakakPI: "Debi Fanessa",
  },
  {
    nama: "AUSTIN AZAREL",
    fakultas: "FV",
    noKel: "10",
    namaKelompok: "Santa",
    kakakKelompok: "Natan",
    kakakPI: "Debi Fanessa",
  },
  {
    nama: "FILIFI GENERALD APRILIUS",
    fakultas: "FT",
    noKel: "10",
    namaKelompok: "Santa",
    kakakKelompok: "Natan",
    kakakPI: "Debi Fanessa",
  },
  {
    nama: "SHEREN MARSELIA LUMBANTORUAN",
    fakultas: "FIK",
    noKel: "10",
    namaKelompok: "Santa",
    kakakKelompok: "Natan",
    kakakPI: "Debi Fanessa",
  },
  {
    nama: "ANGELINA GITA APRILIAN",
    fakultas: "FS",
    noKel: "10",
    namaKelompok: "Santa",
    kakakKelompok: "Natan",
    kakakPI: "Debi Fanessa",
  },
  {
    nama: "CYNTHIA ROWLEY HUTAHAEAN",
    fakultas: "FIP",
    noKel: "10",
    namaKelompok: "Santa",
    kakakKelompok: "Natan",
    kakakPI: "Debi Fanessa",
  },
  {
    nama: "BRIANTO ANJILA",
    fakultas: "FIP",
    noKel: "10",
    namaKelompok: "Santa",
    kakakKelompok: "Natan",
    kakakPI: "Debi Fanessa",
  },
  {
    nama: "NADINE PRICILLIA KALALEMBANG",
    fakultas: "FT",
    noKel: "10",
    namaKelompok: "Santa",
    kakakKelompok: "Natan",
    kakakPI: "Debi Fanessa",
  },
  {
    nama: "ANUGRAH BASTANTA",
    fakultas: "FIS",
    noKel: "11",
    namaKelompok: "Pinus",
    kakakKelompok: "Yere",
    kakakPI: "Bryan Halleluya",
  },
  {
    nama: "VALENCIA PRISTINA LUBIS",
    fakultas: "FIS",
    noKel: "11",
    namaKelompok: "Pinus",
    kakakKelompok: "Yere",
    kakakPI: "Bryan Halleluya",
  },
  {
    nama: "CHELLSY NATHASYA FEODORA MANDA",
    fakultas: "FEB",
    noKel: "11",
    namaKelompok: "Pinus",
    kakakKelompok: "Yere",
    kakakPI: "Bryan Halleluya",
  },
  {
    nama: "ELLY SABET TANI",
    fakultas: "FMIPA",
    noKel: "11",
    namaKelompok: "Pinus",
    kakakKelompok: "Yere",
    kakakPI: "Bryan Halleluya",
  },
  {
    nama: "VANESA ANGGELISA BR GINTING",
    fakultas: "FS",
    noKel: "11",
    namaKelompok: "Pinus",
    kakakKelompok: "Yere",
    kakakPI: "Bryan Halleluya",
  },
  {
    nama: "ALPANI NINA LATERSIA BR SEBAYANG",
    fakultas: "FV",
    noKel: "11",
    namaKelompok: "Pinus",
    kakakKelompok: "Yere",
    kakakPI: "Bryan Halleluya",
  },
  {
    nama: "FRANSISKA E. H. RAISSA BANCIN",
    fakultas: "FT",
    noKel: "11",
    namaKelompok: "Pinus",
    kakakKelompok: "Yere",
    kakakPI: "Bryan Halleluya",
  },
  {
    nama: "ELEAZAR AJAIB SIHDAPMA PUTRA BEYA GAHARU",
    fakultas: "FIK",
    noKel: "11",
    namaKelompok: "Pinus",
    kakakKelompok: "Yere",
    kakakPI: "Bryan Halleluya",
  },
  {
    nama: "FIANEZ KEYSA PUTRI",
    fakultas: "FIP",
    noKel: "11",
    namaKelompok: "Pinus",
    kakakKelompok: "Yere",
    kakakPI: "Bryan Halleluya",
  },
  {
    nama: "EUGENIA FAUSTINE PUNARTO",
    fakultas: "FS",
    noKel: "11",
    namaKelompok: "Pinus",
    kakakKelompok: "Yere",
    kakakPI: "Bryan Halleluya",
  },
  {
    nama: "ADELINE ELVIRA WADU DJAWA",
    fakultas: "FIP",
    noKel: "11",
    namaKelompok: "Pinus",
    kakakKelompok: "Yere",
    kakakPI: "Bryan Halleluya",
  },
  {
    nama: "BINAR DANNO UPENDRA",
    fakultas: "FIS",
    noKel: "12",
    namaKelompok: "Berries",
    kakakKelompok: "Grace",
    kakakPI: "Gleen Pascal",
  },
  {
    nama: "MEIFAN RENATA ESTER HUATABARAT",
    fakultas: "FIS",
    noKel: "12",
    namaKelompok: "Berries",
    kakakKelompok: "Grace",
    kakakPI: "Gleen Pascal",
  },
  {
    nama: "GREY NANDA",
    fakultas: "FEB",
    noKel: "12",
    namaKelompok: "Berries",
    kakakKelompok: "Grace",
    kakakPI: "Gleen Pascal",
  },
  {
    nama: "CLARA PUTRI NATHANELLA",
    fakultas: "FEB",
    noKel: "12",
    namaKelompok: "Berries",
    kakakKelompok: "Grace",
    kakakPI: "Gleen Pascal",
  },
  {
    nama: "ELVIA JOHANNA ANTANG",
    fakultas: "FMIPA",
    noKel: "12",
    namaKelompok: "Berries",
    kakakKelompok: "Grace",
    kakakPI: "Gleen Pascal",
  },
  {
    nama: "AVRAM TETANDHO GUMILANG KASIM",
    fakultas: "FV",
    noKel: "12",
    namaKelompok: "Berries",
    kakakKelompok: "Grace",
    kakakPI: "Gleen Pascal",
  },
  {
    nama: "MICHELE KENZO WIJAYA",
    fakultas: "FS",
    noKel: "12",
    namaKelompok: "Berries",
    kakakKelompok: "Grace",
    kakakPI: "Gleen Pascal",
  },
  {
    nama: "GABRYELLA KOIZUMI BR BUTARBUTAR",
    fakultas: "FT",
    noKel: "12",
    namaKelompok: "Berries",
    kakakKelompok: "Grace",
    kakakPI: "Gleen Pascal",
  },
  {
    nama: "GABRIELLA KARUNIA JULIANA SIANIPAR",
    fakultas: "FIK",
    noKel: "12",
    namaKelompok: "Berries",
    kakakKelompok: "Grace",
    kakakPI: "Gleen Pascal",
  },
  {
    nama: "SHERA OCTAVIA TARIGAN",
    fakultas: "FS",
    noKel: "12",
    namaKelompok: "Berries",
    kakakKelompok: "Grace",
    kakakPI: "Gleen Pascal",
  },
  {
    nama: "FENI GRATIA PANJAITAN",
    fakultas: "FIP",
    noKel: "12",
    namaKelompok: "Berries",
    kakakKelompok: "Grace",
    kakakPI: "Gleen Pascal",
  },
  {
    nama: "DANIEL NINDYA PRIAMBADA",
    fakultas: "FIS",
    noKel: "13",
    namaKelompok: "Snowy",
    kakakKelompok: "Farrel Sang",
    kakakPI: "Alexandra",
  },
  {
    nama: "SARAH CRISTA ZEFANIA",
    fakultas: "FIS",
    noKel: "13",
    namaKelompok: "Snowy",
    kakakKelompok: "Farrel Sang",
    kakakPI: "Alexandra",
  },
  {
    nama: "TAMARO TANATA SITANGGANG",
    fakultas: "FEB",
    noKel: "13",
    namaKelompok: "Snowy",
    kakakKelompok: "Farrel Sang",
    kakakPI: "Alexandra",
  },
  {
    nama: "ELYSABETH RISMA SIMBOLON",
    fakultas: "FMIPA",
    noKel: "13",
    namaKelompok: "Snowy",
    kakakKelompok: "Farrel Sang",
    kakakPI: "Alexandra",
  },
  {
    nama: "ANGELINA MAHARANI",
    fakultas: "FV",
    noKel: "13",
    namaKelompok: "Snowy",
    kakakKelompok: "Farrel Sang",
    kakakPI: "Alexandra",
  },
  {
    nama: "GESCIA PRILLY LIMBONG",
    fakultas: "FT",
    noKel: "13",
    namaKelompok: "Snowy",
    kakakKelompok: "Farrel Sang",
    kakakPI: "Alexandra",
  },
  {
    nama: "VENJELICA PRISKILA STEFANNY",
    fakultas: "FS",
    noKel: "13",
    namaKelompok: "Snowy",
    kakakKelompok: "Farrel Sang",
    kakakPI: "Alexandra",
  },
  {
    nama: "JOSE MARIO CRISNA PRATAMA",
    fakultas: "FIK",
    noKel: "13",
    namaKelompok: "Snowy",
    kakakKelompok: "Farrel Sang",
    kakakPI: "Alexandra",
  },
  {
    nama: "LILIAN NAINGGOLAN",
    fakultas: "FS",
    noKel: "13",
    namaKelompok: "Snowy",
    kakakKelompok: "Farrel Sang",
    kakakPI: "Alexandra",
  },
  {
    nama: "FAREL KRISDIANTO SILABAN",
    fakultas: "FIP",
    noKel: "13",
    namaKelompok: "Snowy",
    kakakKelompok: "Farrel Sang",
    kakakPI: "Alexandra",
  },
  {
    nama: "REYHAN SIREGAR",
    fakultas: "FV",
    noKel: "13",
    namaKelompok: "Snowy",
    kakakKelompok: "Farrel Sang",
    kakakPI: "Alexandra",
  },
  {
    nama: "BENNING LOBIAN",
    fakultas: "FIS",
    noKel: "14",
    namaKelompok: "Cemara",
    kakakKelompok: "Lukas",
    kakakPI: "Hezkya Gultom",
  },
  {
    nama: "SYALOMITHA ANGELINA NABABAN",
    fakultas: "FEB",
    noKel: "14",
    namaKelompok: "Cemara",
    kakakKelompok: "Lukas",
    kakakPI: "Hezkya Gultom",
  },
  {
    nama: "ELYZABETH GITA PUJIONO",
    fakultas: "FMIPA",
    noKel: "14",
    namaKelompok: "Cemara",
    kakakKelompok: "Lukas",
    kakakPI: "Hezkya Gultom",
  },
  {
    nama: "DAVID RAUL KENZO",
    fakultas: "FV",
    noKel: "14",
    namaKelompok: "Cemara",
    kakakKelompok: "Lukas",
    kakakPI: "Hezkya Gultom",
  },
  {
    nama: "GIVEN MARCH RAMSCHIE",
    fakultas: "FT",
    noKel: "14",
    namaKelompok: "Cemara",
    kakakKelompok: "Lukas",
    kakakPI: "Hezkya Gultom",
  },
  {
    nama: "JOSE AXEL CAHYONO",
    fakultas: "FS",
    noKel: "14",
    namaKelompok: "Cemara",
    kakakKelompok: "Lukas",
    kakakPI: "Hezkya Gultom",
  },
  {
    nama: "KARUNIA BULAN KRISHANTY",
    fakultas: "FIK",
    noKel: "14",
    namaKelompok: "Cemara",
    kakakKelompok: "Lukas",
    kakakPI: "Hezkya Gultom",
  },
  {
    nama: "EVANGELINE KEYZIANDIRA ARIZONA",
    fakultas: "FIP",
    noKel: "14",
    namaKelompok: "Cemara",
    kakakKelompok: "Lukas",
    kakakPI: "Hezkya Gultom",
  },
  {
    nama: "CHERIN FEBRINA GULTOM",
    fakultas: "FS",
    noKel: "14",
    namaKelompok: "Cemara",
    kakakKelompok: "Lukas",
    kakakPI: "Hezkya Gultom",
  },
  {
    nama: "CHRISYA DONA MEYNANDA",
    fakultas: "FS",
    noKel: "14",
    namaKelompok: "Cemara",
    kakakKelompok: "Lukas",
    kakakPI: "Hezkya Gultom",
  },
  {
    nama: "BENAYA ANASTHASIUS LAKAUSU",
    fakultas: "FIP",
    noKel: "14",
    namaKelompok: "Cemara",
    kakakKelompok: "Lukas",
    kakakPI: "Hezkya Gultom",
  },
  {
    nama: "ASA YUSTIKA HANDADARI",
    fakultas: "FIS",
    noKel: "15",
    namaKelompok: "Polar",
    kakakKelompok: "Violita",
    kakakPI: "Astrid",
  },
  {
    nama: "REIHAN KAISNA",
    fakultas: "FEB",
    noKel: "15",
    namaKelompok: "Polar",
    kakakKelompok: "Violita",
    kakakPI: "Astrid",
  },
  {
    nama: "CHRISTINE CAECILLIA SANGI",
    fakultas: "FEB",
    noKel: "15",
    namaKelompok: "Polar",
    kakakKelompok: "Violita",
    kakakPI: "Astrid",
  },
  {
    nama: "FIRLEY GRACEA CHRISTY",
    fakultas: "FMIPA",
    noKel: "15",
    namaKelompok: "Polar",
    kakakKelompok: "Violita",
    kakakPI: "Astrid",
  },
  {
    nama: "ANGGIETA PRIZALY NARWASTU SIMARMATA",
    fakultas: "FV",
    noKel: "15",
    namaKelompok: "Polar",
    kakakKelompok: "Violita",
    kakakPI: "Astrid",
  },
  {
    nama: "TITA WILUJENG ANUGRAHA",
    fakultas: "FS",
    noKel: "15",
    namaKelompok: "Polar",
    kakakKelompok: "Violita",
    kakakPI: "Astrid",
  },
  {
    nama: "NOMMENSEN WIRATAMA AMBARITA",
    fakultas: "FIK",
    noKel: "15",
    namaKelompok: "Polar",
    kakakKelompok: "Violita",
    kakakPI: "Astrid",
  },
  {
    nama: "EUNIKE CALYA CAHYANINGRUM",
    fakultas: "FIP",
    noKel: "15",
    namaKelompok: "Polar",
    kakakKelompok: "Violita",
    kakakPI: "Astrid",
  },
  {
    nama: "SHAINA IRENE DWIFARZIL HULU",
    fakultas: "FS",
    noKel: "15",
    namaKelompok: "Polar",
    kakakKelompok: "Violita",
    kakakPI: "Astrid",
  },
  {
    nama: "TIMOTHY AURELIO",
    fakultas: "FT",
    noKel: "15",
    namaKelompok: "Polar",
    kakakKelompok: "Violita",
    kakakPI: "Astrid",
  },
  {
    nama: "RIBKA MARIA",
    fakultas: "FV",
    noKel: "15",
    namaKelompok: "Polar",
    kakakKelompok: "Violita",
    kakakPI: "Astrid",
  },
  {
    nama: "MAUREEN GISELLA TENGES PALAR",
    fakultas: "FT",
    noKel: "15",
    namaKelompok: "Polar",
    kakakKelompok: "Violita",
    kakakPI: "Astrid",
  },
  {
    nama: "JESLYN DIELLA",
    fakultas: "FPSI",
    noKel: "16",
    namaKelompok: "Gletser",
    kakakKelompok: "Anggi",
    kakakPI: "Yosefina",
  },
  {
    nama: "ANGGREINY ERTJIE",
    fakultas: "FIS",
    noKel: "16",
    namaKelompok: "Gletser",
    kakakKelompok: "Anggi",
    kakakPI: "Yosefina",
  },
  {
    nama: "RENITA HALOHO",
    fakultas: "FEB",
    noKel: "16",
    namaKelompok: "Gletser",
    kakakKelompok: "Anggi",
    kakakPI: "Yosefina",
  },
  {
    nama: "GABRIELA PRISKILA SAMBAO",
    fakultas: "FMIPA",
    noKel: "16",
    namaKelompok: "Gletser",
    kakakKelompok: "Anggi",
    kakakPI: "Yosefina",
  },
  {
    nama: "AULIA SAPHIRA ARIANZAH",
    fakultas: "FV",
    noKel: "16",
    namaKelompok: "Gletser",
    kakakKelompok: "Anggi",
    kakakPI: "Yosefina",
  },
  {
    nama: "LEO CANDRIKA LUCY PRABASA",
    fakultas: "FIK",
    noKel: "16",
    namaKelompok: "Gletser",
    kakakKelompok: "Anggi",
    kakakPI: "Yosefina",
  },
  {
    nama: "YULIO ABRAMANDO",
    fakultas: "FS",
    noKel: "16",
    namaKelompok: "Gletser",
    kakakKelompok: "Anggi",
    kakakPI: "Yosefina",
  },
  {
    nama: "ERINA MESYANA PASARIBU",
    fakultas: "FIP",
    noKel: "16",
    namaKelompok: "Gletser",
    kakakKelompok: "Anggi",
    kakakPI: "Yosefina",
  },
  {
    nama: "CHRISTIAN LUFEN BAHARA ADI LEGOWO",
    fakultas: "FIP",
    noKel: "16",
    namaKelompok: "Gletser",
    kakakKelompok: "Anggi",
    kakakPI: "Yosefina",
  },
  {
    nama: "RAFHAEL LAMBA PADANG",
    fakultas: "FT",
    noKel: "16",
    namaKelompok: "Gletser",
    kakakKelompok: "Anggi",
    kakakPI: "Yosefina",
  },
  {
    nama: "SHIFRA GRAVELIE RUMENDE",
    fakultas: "FIP",
    noKel: "16",
    namaKelompok: "Gletser",
    kakakKelompok: "Anggi",
    kakakPI: "Yosefina",
  },
  {
    nama: "KESSIE AGATHA BEREMAU",
    fakultas: "FPSI",
    noKel: "17",
    namaKelompok: "Sakura",
    kakakKelompok: "Titis",
    kakakPI: "Christine Renata",
  },
  {
    nama: "THEO JEREMY GINTING",
    fakultas: "FIS",
    noKel: "17",
    namaKelompok: "Sakura",
    kakakKelompok: "Titis",
    kakakPI: "Christine Renata",
  },
  {
    nama: "RAY RENALDI SITORUS",
    fakultas: "FEB",
    noKel: "17",
    namaKelompok: "Sakura",
    kakakKelompok: "Titis",
    kakakPI: "Christine Renata",
  },
  {
    nama: "JENIFER OKTAVIAH HUTAHAEAN",
    fakultas: "FEB",
    noKel: "17",
    namaKelompok: "Sakura",
    kakakKelompok: "Titis",
    kakakPI: "Christine Renata",
  },
  {
    nama: "GIOVANNY PRASISTA DEWI",
    fakultas: "FMIPA",
    noKel: "17",
    namaKelompok: "Sakura",
    kakakKelompok: "Titis",
    kakakPI: "Christine Renata",
  },
  {
    nama: "CHELLA LUIZE NATALY TAMTELAHITU",
    fakultas: "FV",
    noKel: "17",
    namaKelompok: "Sakura",
    kakakKelompok: "Titis",
    kakakPI: "Christine Renata",
  },
  {
    nama: "JUSAC ALEXIO FRIDO SILAEN",
    fakultas: "FIK",
    noKel: "17",
    namaKelompok: "Sakura",
    kakakKelompok: "Titis",
    kakakPI: "Christine Renata",
  },
  {
    nama: "NUH EKA CHRISTYAN",
    fakultas: "FS",
    noKel: "17",
    namaKelompok: "Sakura",
    kakakKelompok: "Titis",
    kakakPI: "Christine Renata",
  },
  {
    nama: "EMANUELA GLORYA AYU MALAU",
    fakultas: "FIP",
    noKel: "17",
    namaKelompok: "Sakura",
    kakakKelompok: "Titis",
    kakakPI: "Christine Renata",
  },
  {
    nama: "RENATA DWI MARGARET",
    fakultas: "FIP",
    noKel: "17",
    namaKelompok: "Sakura",
    kakakKelompok: "Titis",
    kakakPI: "Christine Renata",
  },
  {
    nama: "RAPHAEL MICHAEL HIU",
    fakultas: "FT",
    noKel: "17",
    namaKelompok: "Sakura",
    kakakKelompok: "Titis",
    kakakPI: "Christine Renata",
  },
  {
    nama: "KEZZIA LAREINA EUODIA",
    fakultas: "FPSI",
    noKel: "18",
    namaKelompok: "Tulip",
    kakakKelompok: "Christo",
    kakakPI: "Rizal Kamma",
  },
  {
    nama: "SAMUEL RADITYA ABEL",
    fakultas: "FIS",
    noKel: "18",
    namaKelompok: "Tulip",
    kakakKelompok: "Christo",
    kakakPI: "Rizal Kamma",
  },
  {
    nama: "ABNER ZANUARD TAMBUNAN",
    fakultas: "FEB",
    noKel: "18",
    namaKelompok: "Tulip",
    kakakKelompok: "Christo",
    kakakPI: "Rizal Kamma",
  },
  {
    nama: "ADELINA BR SEMBIRING",
    fakultas: "FEB",
    noKel: "18",
    namaKelompok: "Tulip",
    kakakKelompok: "Christo",
    kakakPI: "Rizal Kamma",
  },
  {
    nama: "GRACIA DAMAI YANTI ARITONANG",
    fakultas: "FMIPA",
    noKel: "18",
    namaKelompok: "Tulip",
    kakakKelompok: "Christo",
    kakakPI: "Rizal Kamma",
  },
  {
    nama: "RISA YUNI KARSI",
    fakultas: "FK",
    noKel: "18",
    namaKelompok: "Tulip",
    kakakKelompok: "Christo",
    kakakPI: "Rizal Kamma",
  },
  {
    nama: "CHRISTA CAROLINE VANDIRA NUGRAHENI",
    fakultas: "FV",
    noKel: "18",
    namaKelompok: "Tulip",
    kakakKelompok: "Christo",
    kakakPI: "Rizal Kamma",
  },
  {
    nama: "YOSES EMMANUEL BAPTIZE",
    fakultas: "FIK",
    noKel: "18",
    namaKelompok: "Tulip",
    kakakKelompok: "Christo",
    kakakPI: "Rizal Kamma",
  },
  {
    nama: "PRISKILA",
    fakultas: "FS",
    noKel: "18",
    namaKelompok: "Tulip",
    kakakKelompok: "Christo",
    kakakPI: "Rizal Kamma",
  },
  {
    nama: "ELYFEL RIBKHA JIAN CRISTINA",
    fakultas: "FIP",
    noKel: "18",
    namaKelompok: "Tulip",
    kakakKelompok: "Christo",
    kakakPI: "Rizal Kamma",
  },
  {
    nama: "GLENN MARCELLO KRISNA ANANG KUSUMA",
    fakultas: "FS",
    noKel: "18",
    namaKelompok: "Tulip",
    kakakKelompok: "Christo",
    kakakPI: "Rizal Kamma",
  },
  {
    nama: "LIPRIANY SEFANIA YOLANDA TAMBUNAN",
    fakultas: "FPSI",
    noKel: "19",
    namaKelompok: "Melati",
    kakakKelompok: "Prilin",
    kakakPI: "Viola",
  },
  {
    nama: "RIVERALDO VALLENSKIE ALANA EMANUEL",
    fakultas: "FIS",
    noKel: "19",
    namaKelompok: "Melati",
    kakakKelompok: "Prilin",
    kakakPI: "Viola",
  },
  {
    nama: "YOSUA CHRISTIAN WIRATAMA",
    fakultas: "FEB",
    noKel: "19",
    namaKelompok: "Melati",
    kakakKelompok: "Prilin",
    kakakPI: "Viola",
  },
  {
    nama: "EKKLESIA SRI TIENS SIHOMBING",
    fakultas: "FEB",
    noKel: "19",
    namaKelompok: "Melati",
    kakakKelompok: "Prilin",
    kakakPI: "Viola",
  },
  {
    nama: "IIN MARTHEN",
    fakultas: "FMIPA",
    noKel: "19",
    namaKelompok: "Melati",
    kakakKelompok: "Prilin",
    kakakPI: "Viola",
  },
  {
    nama: "NOVRIANUS JASTIN T. LOLU",
    fakultas: "FK",
    noKel: "19",
    namaKelompok: "Melati",
    kakakKelompok: "Prilin",
    kakakPI: "Viola",
  },
  {
    nama: "EDITH CHRISTO SARAGIH",
    fakultas: "FV",
    noKel: "19",
    namaKelompok: "Melati",
    kakakKelompok: "Prilin",
    kakakPI: "Viola",
  },
  {
    nama: "AMELLIA",
    fakultas: "FIK",
    noKel: "19",
    namaKelompok: "Melati",
    kakakKelompok: "Prilin",
    kakakPI: "Viola",
  },
  {
    nama: "DICKNA ADI CASSATRYA",
    fakultas: "FS",
    noKel: "19",
    namaKelompok: "Melati",
    kakakKelompok: "Prilin",
    kakakPI: "Viola",
  },
  {
    nama: "DARLENE OFEL WENGKANG",
    fakultas: "FIP",
    noKel: "19",
    namaKelompok: "Melati",
    kakakKelompok: "Prilin",
    kakakPI: "Viola",
  },
  {
    nama: "ROBERT EVANS NAINGGOLAN",
    fakultas: "FT",
    noKel: "19",
    namaKelompok: "Melati",
    kakakKelompok: "Prilin",
    kakakPI: "Viola",
  },
  {
    nama: "LOVELY SYALLOME BORO",
    fakultas: "FPSI",
    noKel: "20",
    namaKelompok: "Lili",
    kakakKelompok: "",
    kakakPI: "Gabriella Makunimau",
  },
  {
    nama: "REYNARD GABRIEL TOGUDO BUTAR BUTAR",
    fakultas: "FIS",
    noKel: "20",
    namaKelompok: "Lili",
    kakakKelompok: "",
    kakakPI: "Gabriella Makunimau",
  },
  {
    nama: "ABRAHAM SIGRA MARCELINO TAMPUBOLON",
    fakultas: "FEB",
    noKel: "20",
    namaKelompok: "Lili",
    kakakKelompok: "",
    kakakPI: "Gabriella Makunimau",
  },
  {
    nama: "LAURA KUSUMA SRIWARDHANI",
    fakultas: "FEB",
    noKel: "20",
    namaKelompok: "Lili",
    kakakKelompok: "",
    kakakPI: "Gabriella Makunimau",
  },
  {
    nama: "INDAH AULIA HARIANJA",
    fakultas: "FMIPA",
    noKel: "20",
    namaKelompok: "Lili",
    kakakKelompok: "",
    kakakPI: "Gabriella Makunimau",
  },
  {
    nama: "GRACELLA AGATHA",
    fakultas: "FK",
    noKel: "20",
    namaKelompok: "Lili",
    kakakKelompok: "",
    kakakPI: "Gabriella Makunimau",
  },
  {
    nama: "EMMANUEL CALIPSIAS CHRISTOPARELA EMENK",
    fakultas: "FV",
    noKel: "20",
    namaKelompok: "Lili",
    kakakKelompok: "",
    kakakPI: "Gabriella Makunimau",
  },
  {
    nama: "AYU ABIGAIL SITORUS",
    fakultas: "FIK",
    noKel: "20",
    namaKelompok: "Lili",
    kakakKelompok: "",
    kakakPI: "Gabriella Makunimau",
  },
  {
    nama: "ELECTRA EVE ANGELINE SAIYA",
    fakultas: "FS",
    noKel: "20",
    namaKelompok: "Lili",
    kakakKelompok: "",
    kakakPI: "Gabriella Makunimau",
  },
  {
    nama: "DANI SETIAWAN BUTARBUTAR",
    fakultas: "FIP",
    noKel: "20",
    namaKelompok: "Lili",
    kakakKelompok: "",
    kakakPI: "Gabriella Makunimau",
  },
  {
    nama: "SAMUEL STEVEN MANALU",
    fakultas: "FT",
    noKel: "20",
    namaKelompok: "Lili",
    kakakKelompok: "",
    kakakPI: "Gabriella Makunimau",
  },
  {
    nama: "DARIUS DENANDA BAGUS PRASETYA",
    fakultas: "FIS",
    noKel: "21",
    namaKelompok: "Anggrek",
    kakakKelompok: "Adam",
    kakakPI: "Karina",
  },
  {
    nama: "JENIFER MARCIA SUSANTO",
    fakultas: "FIS",
    noKel: "21",
    namaKelompok: "Anggrek",
    kakakKelompok: "Adam",
    kakakPI: "Karina",
  },
  {
    nama: "MUTIARA FAJARYANI LUMBAN TOBING",
    fakultas: "FPSI",
    noKel: "21",
    namaKelompok: "Anggrek",
    kakakKelompok: "Adam",
    kakakPI: "Karina",
  },
  {
    nama: "MARIANA",
    fakultas: "FEB",
    noKel: "21",
    namaKelompok: "Anggrek",
    kakakKelompok: "Adam",
    kakakPI: "Karina",
  },
  {
    nama: "IRENA VITAMA SILITONGA",
    fakultas: "FMIPA",
    noKel: "21",
    namaKelompok: "Anggrek",
    kakakKelompok: "Adam",
    kakakPI: "Karina",
  },
  {
    nama: "YULIAN HARDIANSYAH DWI KRISTIANTO",
    fakultas: "FS",
    noKel: "21",
    namaKelompok: "Anggrek",
    kakakKelompok: "Adam",
    kakakPI: "Karina",
  },
  {
    nama: "GLORIA EKA KURNIA",
    fakultas: "FV",
    noKel: "21",
    namaKelompok: "Anggrek",
    kakakKelompok: "Adam",
    kakakPI: "Karina",
  },
  {
    nama: "GRACIA NATALIANA JOSEFIN SUHARTO",
    fakultas: "FT",
    noKel: "21",
    namaKelompok: "Anggrek",
    kakakKelompok: "Adam",
    kakakPI: "Karina",
  },
  {
    nama: "GHIENZKHA KENZRADA G.E",
    fakultas: "FIK",
    noKel: "21",
    namaKelompok: "Anggrek",
    kakakKelompok: "Adam",
    kakakPI: "Karina",
  },
  {
    nama: "KEZIA AURELIA NUSANTARA",
    fakultas: "FS",
    noKel: "21",
    namaKelompok: "Anggrek",
    kakakKelompok: "Adam",
    kakakPI: "Karina",
  },
  {
    nama: "FINDI EGIS TIANA",
    fakultas: "FIP",
    noKel: "21",
    namaKelompok: "Anggrek",
    kakakKelompok: "Adam",
    kakakPI: "Karina",
  },
  {
    nama: "DAVID TORANG SITORUS",
    fakultas: "FIS",
    noKel: "22",
    namaKelompok: "Mawar",
    kakakKelompok: "Gerald",
    kakakPI: "Nigel",
  },
  {
    nama: "JESICA ANASTASYA TURNIP",
    fakultas: "FIS",
    noKel: "22",
    namaKelompok: "Mawar",
    kakakKelompok: "Gerald",
    kakakPI: "Nigel",
  },
  {
    nama: "NINDA ZEFANYA ROULINA SIDAURUK",
    fakultas: "FPSI",
    noKel: "22",
    namaKelompok: "Mawar",
    kakakKelompok: "Gerald",
    kakakPI: "Nigel",
  },
  {
    nama: "NOVEMBY CHRISTY",
    fakultas: "FEB",
    noKel: "22",
    namaKelompok: "Mawar",
    kakakKelompok: "Gerald",
    kakakPI: "Nigel",
  },
  {
    nama: "KATHERINE ZEFANYA",
    fakultas: "FMIPA",
    noKel: "22",
    namaKelompok: "Mawar",
    kakakKelompok: "Gerald",
    kakakPI: "Nigel",
  },
  {
    nama: "YEHEZKIEL FABIAN PERMANA SETJO",
    fakultas: "FS",
    noKel: "22",
    namaKelompok: "Mawar",
    kakakKelompok: "Gerald",
    kakakPI: "Nigel",
  },
  {
    nama: "GLENN JECONIA JERIKHO",
    fakultas: "FV",
    noKel: "22",
    namaKelompok: "Mawar",
    kakakKelompok: "Gerald",
    kakakPI: "Nigel",
  },
  {
    nama: "JAMES FILIPPUS NAPITUPULU",
    fakultas: "FT",
    noKel: "22",
    namaKelompok: "Mawar",
    kakakKelompok: "Gerald",
    kakakPI: "Nigel",
  },
  {
    nama: "YEMIMA DIAN NESTY",
    fakultas: "FIK",
    noKel: "22",
    namaKelompok: "Mawar",
    kakakKelompok: "Gerald",
    kakakPI: "Nigel",
  },
  {
    nama: "SHENNA ADITYAS",
    fakultas: "FS",
    noKel: "22",
    namaKelompok: "Mawar",
    kakakKelompok: "Gerald",
    kakakPI: "Nigel",
  },
  {
    nama: "GIANETTA ELIAN CHRISANTY",
    fakultas: "FIP",
    noKel: "22",
    namaKelompok: "Mawar",
    kakakKelompok: "Gerald",
    kakakPI: "Nigel",
  },
  {
    nama: "TOBIAS ADE RAMONSYAH SARAGIH",
    fakultas: "FT",
    noKel: "22",
    namaKelompok: "Mawar",
    kakakKelompok: "Gerald",
    kakakPI: "Nigel",
  },
  {
    nama: "EBENEIZER FIRMANDA WIDIAKSONO",
    fakultas: "FIS",
    noKel: "23",
    namaKelompok: "Edelweis",
    kakakKelompok: "Azarya",
    kakakPI: "Azarya",
  },
  {
    nama: "MEICHA DWI VARELLIA",
    fakultas: "FIS",
    noKel: "23",
    namaKelompok: "Edelweis",
    kakakKelompok: "Azarya",
    kakakPI: "Azarya",
  },
  {
    nama: "JONATHAN ISKANDAR",
    fakultas: "FEB",
    noKel: "23",
    namaKelompok: "Edelweis",
    kakakKelompok: "Azarya",
    kakakPI: "Azarya",
  },
  {
    nama: "AMANDA CHRISTY",
    fakultas: "FEB",
    noKel: "23",
    namaKelompok: "Edelweis",
    kakakKelompok: "Azarya",
    kakakPI: "Azarya",
  },
  {
    nama: "KAYLEEN VANESSA KWEE",
    fakultas: "FMIPA",
    noKel: "23",
    namaKelompok: "Edelweis",
    kakakKelompok: "Azarya",
    kakakPI: "Azarya",
  },
  {
    nama: "FINCY SURYANI SILABAN",
    fakultas: "FS",
    noKel: "23",
    namaKelompok: "Edelweis",
    kakakKelompok: "Azarya",
    kakakPI: "Azarya",
  },
  {
    nama: "GITA DEBORA SIMANJUNTAK",
    fakultas: "FV",
    noKel: "23",
    namaKelompok: "Edelweis",
    kakakKelompok: "Azarya",
    kakakPI: "Azarya",
  },
  {
    nama: "JEREMY BOBBY MANNUEL SIMANUNGKALIT",
    fakultas: "FT",
    noKel: "23",
    namaKelompok: "Edelweis",
    kakakKelompok: "Azarya",
    kakakPI: "Azarya",
  },
  {
    nama: "FRISKILA TITANIA",
    fakultas: "FIK",
    noKel: "23",
    namaKelompok: "Edelweis",
    kakakKelompok: "Azarya",
    kakakPI: "Azarya",
  },
  {
    nama: "ADINE SEPTIA HOSANA TRI PUTRI",
    fakultas: "FS",
    noKel: "23",
    namaKelompok: "Edelweis",
    kakakKelompok: "Azarya",
    kakakPI: "Azarya",
  },
  {
    nama: "GLORIA KURNIASAKTI",
    fakultas: "FIP",
    noKel: "23",
    namaKelompok: "Edelweis",
    kakakKelompok: "Azarya",
    kakakPI: "Azarya",
  },
  {
    nama: "TOHAP MANALU",
    fakultas: "FT",
    noKel: "23",
    namaKelompok: "Edelweis",
    kakakKelompok: "Azarya",
    kakakPI: "Azarya",
  },
  {
    nama: "CECILLIA EGYPTA MOZZA ANDUWATJU",
    fakultas: "FIS",
    noKel: "24",
    namaKelompok: "Mekar",
    kakakKelompok: "Ariel Biancha",
    kakakPI: "Ariel Biancha",
  },
  {
    nama: "ANDIKA BINTANG PUTRA PRATAMA",
    fakultas: "FEB",
    noKel: "24",
    namaKelompok: "Mekar",
    kakakKelompok: "Ariel Biancha",
    kakakPI: "Ariel Biancha",
  },
  {
    nama: "HENY PUTRI DARRA",
    fakultas: "FEB",
    noKel: "24",
    namaKelompok: "Mekar",
    kakakKelompok: "Ariel Biancha",
    kakakPI: "Ariel Biancha",
  },
  {
    nama: "KEISHA AURELIA BUTAR BUTAR",
    fakultas: "FMIPA",
    noKel: "24",
    namaKelompok: "Mekar",
    kakakKelompok: "Ariel Biancha",
    kakakPI: "Ariel Biancha",
  },
  {
    nama: "CYNTIA APRILIA",
    fakultas: "FK",
    noKel: "24",
    namaKelompok: "Mekar",
    kakakKelompok: "Ariel Biancha",
    kakakPI: "Ariel Biancha",
  },
  {
    nama: "GIFT THEO VALENTINO",
    fakultas: "FV",
    noKel: "24",
    namaKelompok: "Mekar",
    kakakKelompok: "Ariel Biancha",
    kakakPI: "Ariel Biancha",
  },
  {
    nama: "YVONNE ANTONETTA IMANUELLA",
    fakultas: "FS",
    noKel: "24",
    namaKelompok: "Mekar",
    kakakKelompok: "Ariel Biancha",
    kakakPI: "Ariel Biancha",
  },
  {
    nama: "JESIKA YEREMIA",
    fakultas: "FT",
    noKel: "24",
    namaKelompok: "Mekar",
    kakakKelompok: "Ariel Biancha",
    kakakPI: "Ariel Biancha",
  },
  {
    nama: "RIUS SIMON",
    fakultas: "FIK",
    noKel: "24",
    namaKelompok: "Mekar",
    kakakKelompok: "Ariel Biancha",
    kakakPI: "Ariel Biancha",
  },
  {
    nama: "GRACIELA ATALYA SAPTUS",
    fakultas: "FIP",
    noKel: "24",
    namaKelompok: "Mekar",
    kakakKelompok: "Ariel Biancha",
    kakakPI: "Ariel Biancha",
  },
  {
    nama: "YOANA CELIN RIANI SIREGAR",
    fakultas: "FS",
    noKel: "24",
    namaKelompok: "Mekar",
    kakakKelompok: "Ariel Biancha",
    kakakPI: "Ariel Biancha",
  },
  {
    nama: "YEHEZKIEL DUTA SABATHANI",
    fakultas: "FT",
    noKel: "24",
    namaKelompok: "Mekar",
    kakakKelompok: "Ariel Biancha",
    kakakPI: "Ariel Biancha",
  },
  {
    nama: "CLARISA IVANA FIRLY",
    fakultas: "FIS",
    noKel: "25",
    namaKelompok: "Fajar",
    kakakKelompok: "Clariza",
    kakakPI: "Clariza",
  },
  {
    nama: "AUDRIANA CALLISTA PUTRI",
    fakultas: "FEB",
    noKel: "25",
    namaKelompok: "Fajar",
    kakakKelompok: "Clariza",
    kakakPI: "Clariza",
  },
  {
    nama: "KEYSHIA NATASIA PUTRI SURBAKTI",
    fakultas: "FMIPA",
    noKel: "25",
    namaKelompok: "Fajar",
    kakakKelompok: "Clariza",
    kakakPI: "Clariza",
  },
  {
    nama: "CLAUDEA SEFA APRILICA",
    fakultas: "FK",
    noKel: "25",
    namaKelompok: "Fajar",
    kakakKelompok: "Clariza",
    kakakPI: "Clariza",
  },
  {
    nama: "FIRES ARKA WISESA",
    fakultas: "FV",
    noKel: "25",
    namaKelompok: "Fajar",
    kakakKelompok: "Clariza",
    kakakPI: "Clariza",
  },
  {
    nama: "FRANSZECHA AZARYA SIREGAR",
    fakultas: "FS",
    noKel: "25",
    namaKelompok: "Fajar",
    kakakKelompok: "Clariza",
    kakakPI: "Clariza",
  },
  {
    nama: "JOAN PANGARAWAHENU",
    fakultas: "FT",
    noKel: "25",
    namaKelompok: "Fajar",
    kakakKelompok: "Clariza",
    kakakPI: "Clariza",
  },
  {
    nama: "KRISTIAN RONALDO",
    fakultas: "FIK",
    noKel: "25",
    namaKelompok: "Fajar",
    kakakKelompok: "Clariza",
    kakakPI: "Clariza",
  },
  {
    nama: "GRACIELLA JOSHUA AGONI",
    fakultas: "FIP",
    noKel: "25",
    namaKelompok: "Fajar",
    kakakKelompok: "Clariza",
    kakakPI: "Clariza",
  },
  {
    nama: "YOSHUA OKTAVIO ARDY RAMADHANI",
    fakultas: "FT",
    noKel: "25",
    namaKelompok: "Fajar",
    kakakKelompok: "Clariza",
    kakakPI: "Clariza",
  },
  {
    nama: "RIBKA ANGELA VIRGINIA SITOMPUL",
    fakultas: "FV",
    noKel: "25",
    namaKelompok: "Fajar",
    kakakKelompok: "Clariza",
    kakakPI: "Clariza",
  },
  {
    nama: "MOSES SIVAN",
    fakultas: "FIP",
    noKel: "25",
    namaKelompok: "Fajar",
    kakakKelompok: "Clariza",
    kakakPI: "Clariza",
  },
  {
    nama: "DIOXVEL SHARAPOVA PRIYANTOYO",
    fakultas: "FIS",
    noKel: "26",
    namaKelompok: "Mentari",
    kakakKelompok: "Gabriel Calvin",
    kakakPI: "Marcella",
  },
  {
    nama: "CHRISTIAN MANUELA JAVAZ",
    fakultas: "FEB",
    noKel: "26",
    namaKelompok: "Mentari",
    kakakKelompok: "Gabriel Calvin",
    kakakPI: "Marcella",
  },
  {
    nama: "KEZIA VALERINA NAOMI NDJURUMANA",
    fakultas: "FEB",
    noKel: "26",
    namaKelompok: "Mentari",
    kakakKelompok: "Gabriel Calvin",
    kakakPI: "Marcella",
  },
  {
    nama: "KRISTANTI LOUISIANA PUTRI SINAGA",
    fakultas: "FMIPA",
    noKel: "26",
    namaKelompok: "Mentari",
    kakakKelompok: "Gabriel Calvin",
    kakakPI: "Marcella",
  },
  {
    nama: "EXCEL DEREN STERLINO",
    fakultas: "FV",
    noKel: "26",
    namaKelompok: "Mentari",
    kakakKelompok: "Gabriel Calvin",
    kakakPI: "Marcella",
  },
  {
    nama: "ALVA JANETTA CHRISTY WIBAWA",
    fakultas: "FS",
    noKel: "26",
    namaKelompok: "Mentari",
    kakakKelompok: "Gabriel Calvin",
    kakakPI: "Marcella",
  },
  {
    nama: "JONATHAN SHANE DAVIS",
    fakultas: "FT",
    noKel: "26",
    namaKelompok: "Mentari",
    kakakKelompok: "Gabriel Calvin",
    kakakPI: "Marcella",
  },
  {
    nama: "NOVITA ELIZA LOIDA DAMANIK",
    fakultas: "FIK",
    noKel: "26",
    namaKelompok: "Mentari",
    kakakKelompok: "Gabriel Calvin",
    kakakPI: "Marcella",
  },
  {
    nama: "HENRIETTA ESTER FEBRIANA",
    fakultas: "FIP",
    noKel: "26",
    namaKelompok: "Mentari",
    kakakKelompok: "Gabriel Calvin",
    kakakPI: "Marcella",
  },
  {
    nama: "YOSUA CHRISTIAN NATANA PRASETIYO",
    fakultas: "FT",
    noKel: "26",
    namaKelompok: "Mentari",
    kakakKelompok: "Gabriel Calvin",
    kakakPI: "Marcella",
  },
  {
    nama: "ANINDYA GALUH MAHESWARI",
    fakultas: "FIP",
    noKel: "26",
    namaKelompok: "Mentari",
    kakakKelompok: "Gabriel Calvin",
    kakakPI: "Marcella",
  },
  {
    nama: "ELBANIA TRIFENA JENIFER MALAMUK",
    fakultas: "FIS",
    noKel: "27",
    namaKelompok: "Kenari",
    kakakKelompok: "Nadya",
    kakakPI: "Rahayu Ester",
  },
  {
    nama: "BETUEL KEVIN SEO",
    fakultas: "FEB",
    noKel: "27",
    namaKelompok: "Kenari",
    kakakKelompok: "Nadya",
    kakakPI: "Rahayu Ester",
  },
  {
    nama: "CHRISSABELLA LOVELY MICHELLE",
    fakultas: "FEB",
    noKel: "27",
    namaKelompok: "Kenari",
    kakakKelompok: "Nadya",
    kakakPI: "Rahayu Ester",
  },
  {
    nama: "MARGARETHA GITA PUJIONO",
    fakultas: "FMIPA",
    noKel: "27",
    namaKelompok: "Kenari",
    kakakKelompok: "Nadya",
    kakakPI: "Rahayu Ester",
  },
  {
    nama: "ESTI IRIN HUTABARAT",
    fakultas: "FV",
    noKel: "27",
    namaKelompok: "Kenari",
    kakakKelompok: "Nadya",
    kakakPI: "Rahayu Ester",
  },
  {
    nama: "VINCENT ADRIAN NABABAN",
    fakultas: "FMIPA",
    noKel: "27",
    namaKelompok: "Kenari",
    kakakKelompok: "Nadya",
    kakakPI: "Rahayu Ester",
  },
  {
    nama: "JONATHAN VALENTINO BAUDA",
    fakultas: "FT",
    noKel: "27",
    namaKelompok: "Kenari",
    kakakKelompok: "Nadya",
    kakakPI: "Rahayu Ester",
  },
  {
    nama: "ARTARA KASIH JOSELIN",
    fakultas: "FS",
    noKel: "27",
    namaKelompok: "Kenari",
    kakakKelompok: "Nadya",
    kakakPI: "Rahayu Ester",
  },
  {
    nama: "VANIA OZORA AZALIA AGATHA",
    fakultas: "FIK",
    noKel: "27",
    namaKelompok: "Kenari",
    kakakKelompok: "Nadya",
    kakakPI: "Rahayu Ester",
  },
  {
    nama: "HERLINA",
    fakultas: "FIP",
    noKel: "27",
    namaKelompok: "Kenari",
    kakakKelompok: "Nadya",
    kakakPI: "Rahayu Ester",
  },
  {
    nama: "YUDA TRIATMAN NAIBAHO",
    fakultas: "FT",
    noKel: "27",
    namaKelompok: "Kenari",
    kakakKelompok: "Nadya",
    kakakPI: "Rahayu Ester",
  },
  {
    nama: "ELXARIS MEISYA FARALLESA",
    fakultas: "FIS",
    noKel: "28",
    namaKelompok: "Angin",
    kakakKelompok: "Jevon",
    kakakPI: "Easter",
  },
  {
    nama: "HANA PRISKILA PARDEDE",
    fakultas: "FEB",
    noKel: "28",
    namaKelompok: "Angin",
    kakakKelompok: "Jevon",
    kakakPI: "Easter",
  },
  {
    nama: "MIRANDA QUIN OYAITOUW",
    fakultas: "FMIPA",
    noKel: "28",
    namaKelompok: "Angin",
    kakakKelompok: "Jevon",
    kakakPI: "Easter",
  },
  {
    nama: "GHEA IGNACIA",
    fakultas: "FK",
    noKel: "28",
    namaKelompok: "Angin",
    kakakKelompok: "Jevon",
    kakakPI: "Easter",
  },
  {
    nama: "ESTER MARSHA AULIA",
    fakultas: "FV",
    noKel: "28",
    namaKelompok: "Angin",
    kakakKelompok: "Jevon",
    kakakPI: "Easter",
  },
  {
    nama: "VEBRIEL MAHA PUTRA ZILIWU",
    fakultas: "FMIPA",
    noKel: "28",
    namaKelompok: "Angin",
    kakakKelompok: "Jevon",
    kakakPI: "Easter",
  },
  {
    nama: "NATHANIA BELANI ESTU SETIANTO",
    fakultas: "FIK",
    noKel: "28",
    namaKelompok: "Angin",
    kakakKelompok: "Jevon",
    kakakPI: "Easter",
  },
  {
    nama: "JOVANDE SAMADI",
    fakultas: "FT",
    noKel: "28",
    namaKelompok: "Angin",
    kakakKelompok: "Jevon",
    kakakPI: "Easter",
  },
  {
    nama: "GRISELDA MIRELLA DIANTHI",
    fakultas: "FS",
    noKel: "28",
    namaKelompok: "Angin",
    kakakKelompok: "Jevon",
    kakakPI: "Easter",
  },
  {
    nama: "IRENE RAMBU DUPA OLIHANJATA",
    fakultas: "FIP",
    noKel: "28",
    namaKelompok: "Angin",
    kakakKelompok: "Jevon",
    kakakPI: "Easter",
  },
  {
    nama: "YUNI LILYANITA",
    fakultas: "FT",
    noKel: "28",
    namaKelompok: "Angin",
    kakakKelompok: "Jevon",
    kakakPI: "Easter",
  },
  {
    nama: "ERSZHEL NAFTALIF SIHOMBING",
    fakultas: "FIS",
    noKel: "29",
    namaKelompok: "Dandelion",
    kakakKelompok: "Meycha",
    kakakPI: "Meycha",
  },
  {
    nama: "NAOMI AULINA SIANTURI",
    fakultas: "FEB",
    noKel: "29",
    namaKelompok: "Dandelion",
    kakakKelompok: "Meycha",
    kakakPI: "Meycha",
  },
  {
    nama: "NAFTALIA RIEGANANDA PUTRI",
    fakultas: "FMIPA",
    noKel: "29",
    namaKelompok: "Dandelion",
    kakakKelompok: "Meycha",
    kakakPI: "Meycha",
  },
  {
    nama: "ERYNDA INTAN PRATIWI",
    fakultas: "FV",
    noKel: "29",
    namaKelompok: "Dandelion",
    kakakKelompok: "Meycha",
    kakakPI: "Meycha",
  },
  {
    nama: "STEVEN GERRARD NATHANAEL SIMANGUNSONG",
    fakultas: "FMIPA",
    noKel: "29",
    namaKelompok: "Dandelion",
    kakakKelompok: "Meycha",
    kakakPI: "Meycha",
  },
  {
    nama: "FAREL CRISTIAN PATULAK",
    fakultas: "FIK",
    noKel: "29",
    namaKelompok: "Dandelion",
    kakakKelompok: "Meycha",
    kakakPI: "Meycha",
  },
  {
    nama: "JOYCE ASTERIA MANURUNG",
    fakultas: "FT",
    noKel: "29",
    namaKelompok: "Dandelion",
    kakakKelompok: "Meycha",
    kakakPI: "Meycha",
  },
  {
    nama: "STEVIE NATHANIA DOTIE",
    fakultas: "FS",
    noKel: "29",
    namaKelompok: "Dandelion",
    kakakKelompok: "Meycha",
    kakakPI: "Meycha",
  },
  {
    nama: "JELITA HENI RAMADANI MANI HURUK",
    fakultas: "FIP",
    noKel: "29",
    namaKelompok: "Dandelion",
    kakakKelompok: "Meycha",
    kakakPI: "Meycha",
  },
  {
    nama: "ZEPPELYN AMADHEO YUANTA",
    fakultas: "FT",
    noKel: "29",
    namaKelompok: "Dandelion",
    kakakKelompok: "Meycha",
    kakakPI: "Meycha",
  },
  {
    nama: "RACHEL SANDY SUDARMONOO",
    fakultas: "FIP",
    noKel: "29",
    namaKelompok: "Dandelion",
    kakakKelompok: "Meycha",
    kakakPI: "Meycha",
  },
  {
    nama: "GRACIA NATALIE CAHYADI",
    fakultas: "FIS",
    noKel: "30",
    namaKelompok: "Lavender",
    kakakKelompok: "Gelsie",
    kakakPI: "Gelsie",
  },
  {
    nama: "GOSYEN GABRIEL M. SIMANJUNTAK",
    fakultas: "FEB",
    noKel: "30",
    namaKelompok: "Lavender",
    kakakKelompok: "Gelsie",
    kakakPI: "Gelsie",
  },
  {
    nama: "ALINE GERA SAVANA",
    fakultas: "FEB",
    noKel: "30",
    namaKelompok: "Lavender",
    kakakKelompok: "Gelsie",
    kakakPI: "Gelsie",
  },
  {
    nama: "ROHANA ULI HUTAPEA",
    fakultas: "FMIPA",
    noKel: "30",
    namaKelompok: "Lavender",
    kakakKelompok: "Gelsie",
    kakakPI: "Gelsie",
  },
  {
    nama: "ERICK RUBEN ARDHANA",
    fakultas: "FV",
    noKel: "30",
    namaKelompok: "Lavender",
    kakakKelompok: "Gelsie",
    kakakPI: "Gelsie",
  },
  {
    nama: "SANDRO MORA NAINGGOLAN",
    fakultas: "FMIPA",
    noKel: "30",
    namaKelompok: "Lavender",
    kakakKelompok: "Gelsie",
    kakakPI: "Gelsie",
  },
  {
    nama: "ANDHERSON CELVIN GIOVANNI",
    fakultas: "FIK",
    noKel: "30",
    namaKelompok: "Lavender",
    kakakKelompok: "Gelsie",
    kakakPI: "Gelsie",
  },
  {
    nama: "KASIH CHRISTIANA MAGDALENA PANJAITAN",
    fakultas: "FT",
    noKel: "30",
    namaKelompok: "Lavender",
    kakakKelompok: "Gelsie",
    kakakPI: "Gelsie",
  },
  {
    nama: "EUNIKE LOUISA WIRANTI RAHARJO",
    fakultas: "FS",
    noKel: "30",
    namaKelompok: "Lavender",
    kakakKelompok: "Gelsie",
    kakakPI: "Gelsie",
  },
  {
    nama: "JESSICA AULIA ANABELLA MARBUN",
    fakultas: "FIP",
    noKel: "30",
    namaKelompok: "Lavender",
    kakakKelompok: "Gelsie",
    kakakPI: "Gelsie",
  },
  {
    nama: "MARCELLO CAVIANO POTORU",
    fakultas: "FT",
    noKel: "30",
    namaKelompok: "Lavender",
    kakakKelompok: "Gelsie",
    kakakPI: "Gelsie",
  },
  {
    nama: "ZEFANYA EDENIA PRASETYO",
    fakultas: "FEB",
    noKel: "31",
    namaKelompok: "Maple",
    kakakKelompok: "Gracia Rutia",
    kakakPI: "Gracia Rutia",
  },
  {
    nama: "YOWANDA STEVANY TAOSU",
    fakultas: "FIS",
    noKel: "31",
    namaKelompok: "Maple",
    kakakKelompok: "Gracia Rutia",
    kakakPI: "Gracia Rutia",
  },
  {
    nama: "THESALONIKA VIONA TARIGAN",
    fakultas: "FMIPA",
    noKel: "31",
    namaKelompok: "Maple",
    kakakKelompok: "Gracia Rutia",
    kakakPI: "Gracia Rutia",
  },
  {
    nama: "ARISTA YOVITA LUKININGTYAS",
    fakultas: "FS",
    noKel: "31",
    namaKelompok: "Maple",
    kakakKelompok: "Gracia Rutia",
    kakakPI: "Gracia Rutia",
  },
  {
    nama: "GILBY CHRISTIAN UTOMO",
    fakultas: "FMIPA",
    noKel: "31",
    namaKelompok: "Maple",
    kakakKelompok: "Gracia Rutia",
    kakakPI: "Gracia Rutia",
  },
  {
    nama: "GLORIA PASKAH PRAMUDITHA LOLO",
    fakultas: "FV",
    noKel: "31",
    namaKelompok: "Maple",
    kakakKelompok: "Gracia Rutia",
    kakakPI: "Gracia Rutia",
  },
  {
    nama: "JUAN ALTER WAHYUDI",
    fakultas: "FT",
    noKel: "31",
    namaKelompok: "Maple",
    kakakKelompok: "Gracia Rutia",
    kakakPI: "Gracia Rutia",
  },
  {
    nama: "NATASHA GRACIELLA PUTRI EFENDI",
    fakultas: "FS",
    noKel: "31",
    namaKelompok: "Maple",
    kakakKelompok: "Gracia Rutia",
    kakakPI: "Gracia Rutia",
  },
  {
    nama: "PUSPA KIRANA",
    fakultas: "FIP",
    noKel: "31",
    namaKelompok: "Maple",
    kakakKelompok: "Gracia Rutia",
    kakakPI: "Gracia Rutia",
  },
  {
    nama: "REYFIDELA CORDELIA SARAGIH",
    fakultas: "FT",
    noKel: "31",
    namaKelompok: "Maple",
    kakakKelompok: "Gracia Rutia",
    kakakPI: "Gracia Rutia",
  },
  {
    nama: "NADIA PUTRI ARDIYANTI",
    fakultas: "FT",
    noKel: "31",
    namaKelompok: "Maple",
    kakakKelompok: "Gracia Rutia",
    kakakPI: "Gracia Rutia",
  },
  {
    nama: "FRENSAH KALAWAY",
    fakultas: "FIS",
    noKel: "32",
    namaKelompok: "Tupai",
    kakakKelompok: "Riris Tama",
    kakakPI: "Riris Tama",
  },
  {
    nama: "AUDRY JACINDA PARAHITA GUNAWAN",
    fakultas: "FIS",
    noKel: "32",
    namaKelompok: "Tupai",
    kakakKelompok: "Riris Tama",
    kakakPI: "Riris Tama",
  },
  {
    nama: "REBECA SIHITE",
    fakultas: "FPSI",
    noKel: "32",
    namaKelompok: "Tupai",
    kakakKelompok: "Riris Tama",
    kakakPI: "Riris Tama",
  },
  {
    nama: "JESICA AUDIA",
    fakultas: "FEB",
    noKel: "32",
    namaKelompok: "Tupai",
    kakakKelompok: "Riris Tama",
    kakakPI: "Riris Tama",
  },
  {
    nama: "SULUH TIANGGUR SIAGIAN",
    fakultas: "FMIPA",
    noKel: "32",
    namaKelompok: "Tupai",
    kakakKelompok: "Riris Tama",
    kakakPI: "Riris Tama",
  },
  {
    nama: "GAMALIEL ORLIEN PASKAHLYA RIEUWPASSA",
    fakultas: "FS",
    noKel: "32",
    namaKelompok: "Tupai",
    kakakKelompok: "Riris Tama",
    kakakPI: "Riris Tama",
  },
  {
    nama: "GLEND ALINSKI NATANAEL",
    fakultas: "FMIPA",
    noKel: "32",
    namaKelompok: "Tupai",
    kakakKelompok: "Riris Tama",
    kakakPI: "Riris Tama",
  },
  {
    nama: "GRACE SHILA NEISHA SIRAIT",
    fakultas: "FV",
    noKel: "32",
    namaKelompok: "Tupai",
    kakakKelompok: "Riris Tama",
    kakakPI: "Riris Tama",
  },
  {
    nama: "KEYZIA EL FHANIO",
    fakultas: "FT",
    noKel: "32",
    namaKelompok: "Tupai",
    kakakKelompok: "Riris Tama",
    kakakPI: "Riris Tama",
  },
  {
    nama: "ZEFANYA BELLA TAMPUBOLON",
    fakultas: "FS",
    noKel: "32",
    namaKelompok: "Tupai",
    kakakKelompok: "Riris Tama",
    kakakPI: "Riris Tama",
  },
  {
    nama: "PRISKILA AGUSTINA SETIANI",
    fakultas: "FIP",
    noKel: "32",
    namaKelompok: "Tupai",
    kakakKelompok: "Riris Tama",
    kakakPI: "Riris Tama",
  },
  {
    nama: "STEVEN DWIGHT SUGITO",
    fakultas: "FT",
    noKel: "32",
    namaKelompok: "Tupai",
    kakakKelompok: "Riris Tama",
    kakakPI: "Riris Tama",
  },
  {
    nama: "JOSHUA FAREL DWI ANDHIKA",
    fakultas: "FIS",
    noKel: "33",
    namaKelompok: "Hujan",
    kakakKelompok: "Evangeline C",
    kakakPI: "Evangeline C",
  },
  {
    nama: "AZALIA YSIDORA SERA",
    fakultas: "FIS",
    noKel: "33",
    namaKelompok: "Hujan",
    kakakKelompok: "Evangeline C",
    kakakPI: "Evangeline C",
  },
  {
    nama: "TESYAH LENARMA SINAGA",
    fakultas: "FPSI",
    noKel: "33",
    namaKelompok: "Hujan",
    kakakKelompok: "Evangeline C",
    kakakPI: "Evangeline C",
  },
  {
    nama: "PIETER EFESUS",
    fakultas: "FEB",
    noKel: "33",
    namaKelompok: "Hujan",
    kakakKelompok: "Evangeline C",
    kakakPI: "Evangeline C",
  },
  {
    nama: "ANNISA MEI DINA",
    fakultas: "FEB",
    noKel: "33",
    namaKelompok: "Hujan",
    kakakKelompok: "Evangeline C",
    kakakPI: "Evangeline C",
  },
  {
    nama: "SIREN AGUSTINA BANGUN",
    fakultas: "FMIPA",
    noKel: "33",
    namaKelompok: "Hujan",
    kakakKelompok: "Evangeline C",
    kakakPI: "Evangeline C",
  },
  {
    nama: "CHRIZYA ALITA PUTRI",
    fakultas: "FK",
    noKel: "33",
    namaKelompok: "Hujan",
    kakakKelompok: "Evangeline C",
    kakakPI: "Evangeline C",
  },
  {
    nama: "HIZKIA SYALOM SETYADI",
    fakultas: "FMIPA",
    noKel: "33",
    namaKelompok: "Hujan",
    kakakKelompok: "Evangeline C",
    kakakPI: "Evangeline C",
  },
  {
    nama: "JEREMY BRIAN CHRISTIAN",
    fakultas: "FS",
    noKel: "33",
    namaKelompok: "Hujan",
    kakakKelompok: "Evangeline C",
    kakakPI: "Evangeline C",
  },
  {
    nama: "GREATY MERCY NATANIA",
    fakultas: "FV",
    noKel: "33",
    namaKelompok: "Hujan",
    kakakKelompok: "Evangeline C",
    kakakPI: "Evangeline C",
  },
  {
    nama: "SIONG FAH CIN",
    fakultas: "FIK",
    noKel: "33",
    namaKelompok: "Hujan",
    kakakKelompok: "Evangeline C",
    kakakPI: "Evangeline C",
  },
  {
    nama: "NATALIA ELISABETD PARDEDE",
    fakultas: "FS",
    noKel: "33",
    namaKelompok: "Hujan",
    kakakKelompok: "Evangeline C",
    kakakPI: "Evangeline C",
  },
  {
    nama: "JOSIA MARSEL TERDINANTA",
    fakultas: "FIS",
    noKel: "34",
    namaKelompok: "Awan",
    kakakKelompok: "Vhioley I",
    kakakPI: "Vhioley I",
  },
  {
    nama: "CASELLIA ELISABETHANI SYELOMITHA SIMANULLANG",
    fakultas: "FIS",
    noKel: "34",
    namaKelompok: "Awan",
    kakakKelompok: "Vhioley I",
    kakakPI: "Vhioley I",
  },
  {
    nama: "VANESSA EMANUELLA BR GINTING",
    fakultas: "FPSI",
    noKel: "34",
    namaKelompok: "Awan",
    kakakKelompok: "Vhioley I",
    kakakPI: "Vhioley I",
  },
  {
    nama: "NINDI EKA PRASETYA",
    fakultas: "FEB",
    noKel: "34",
    namaKelompok: "Awan",
    kakakKelompok: "Vhioley I",
    kakakPI: "Vhioley I",
  },
  {
    nama: "SIDABUTAR CHRISTINE FLORA ROMAULI",
    fakultas: "FMIPA",
    noKel: "34",
    namaKelompok: "Awan",
    kakakKelompok: "Vhioley I",
    kakakPI: "Vhioley I",
  },
  {
    nama: "HOSEA H SIMATUPANG",
    fakultas: "FMIPA",
    noKel: "34",
    namaKelompok: "Awan",
    kakakKelompok: "Vhioley I",
    kakakPI: "Vhioley I",
  },
  {
    nama: "GULTOM CHRISTINE EVELYN",
    fakultas: "FV",
    noKel: "34",
    namaKelompok: "Awan",
    kakakKelompok: "Vhioley I",
    kakakPI: "Vhioley I",
  },
  {
    nama: "HARDEV EDYTH TRISNOJATI",
    fakultas: "FS",
    noKel: "34",
    namaKelompok: "Awan",
    kakakKelompok: "Vhioley I",
    kakakPI: "Vhioley I",
  },
  {
    nama: "NATALIA ELSADAI GLORIA",
    fakultas: "FIK",
    noKel: "34",
    namaKelompok: "Awan",
    kakakKelompok: "Vhioley I",
    kakakPI: "Vhioley I",
  },
  {
    nama: "LOULY LOULEN SIBARANI",
    fakultas: "FT",
    noKel: "34",
    namaKelompok: "Awan",
    kakakKelompok: "Vhioley I",
    kakakPI: "Vhioley I",
  },
  {
    nama: "MICHELLE PAPUANA PUTRI MUDJU",
    fakultas: "FS",
    noKel: "34",
    namaKelompok: "Awan",
    kakakKelompok: "Vhioley I",
    kakakPI: "Vhioley I",
  },
  {
    nama: "MARIA JOCEVA BR SIANTURI",
    fakultas: "FIP",
    noKel: "34",
    namaKelompok: "Awan",
    kakakKelompok: "Vhioley I",
    kakakPI: "Vhioley I",
  },
  {
    nama: "RATRI WIBOWO",
    fakultas: "FIS",
    noKel: "35",
    namaKelompok: "Senja",
    kakakKelompok: "Raelisa K",
    kakakPI: "Raelisa K",
  },
  {
    nama: "DIVANIA TURNIP",
    fakultas: "FEB",
    noKel: "35",
    namaKelompok: "Senja",
    kakakKelompok: "Raelisa K",
    kakakPI: "Raelisa K",
  },
  {
    nama: "SIBURIAN EVA MARIANA",
    fakultas: "FMIPA",
    noKel: "35",
    namaKelompok: "Senja",
    kakakKelompok: "Raelisa K",
    kakakPI: "Raelisa K",
  },
  {
    nama: "JASON RAGIL PANOGARI",
    fakultas: "FMIPA",
    noKel: "35",
    namaKelompok: "Senja",
    kakakKelompok: "Raelisa K",
    kakakPI: "Raelisa K",
  },
  {
    nama: "I MADE ARUDEA DENIAFINDER GOTAMA",
    fakultas: "FV",
    noKel: "35",
    namaKelompok: "Senja",
    kakakKelompok: "Raelisa K",
    kakakPI: "Raelisa K",
  },
  {
    nama: "DANIELA RADITHA SIPAHELUT",
    fakultas: "FS",
    noKel: "35",
    namaKelompok: "Senja",
    kakakKelompok: "Raelisa K",
    kakakPI: "Raelisa K",
  },
  {
    nama: "PUJI FEBRIANTI BR MARPAUNG",
    fakultas: "FIK",
    noKel: "35",
    namaKelompok: "Senja",
    kakakKelompok: "Raelisa K",
    kakakPI: "Raelisa K",
  },
  {
    nama: "MADE ELNATHAN A. G.",
    fakultas: "FT",
    noKel: "35",
    namaKelompok: "Senja",
    kakakKelompok: "Raelisa K",
    kakakPI: "Raelisa K",
  },
  {
    nama: "LOUIS ALVIUS BUDHI PRAPANCA",
    fakultas: "FIP",
    noKel: "35",
    namaKelompok: "Senja",
    kakakKelompok: "Raelisa K",
    kakakPI: "Raelisa K",
  },
  {
    nama: "STEVIA EFRIANTI PALINOAN",
    fakultas: "FT",
    noKel: "35",
    namaKelompok: "Senja",
    kakakKelompok: "Raelisa K",
    kakakPI: "Raelisa K",
  },
  {
    nama: "TAMARISKA KRISTANTI PERTIWI",
    fakultas: "FIP",
    noKel: "35",
    namaKelompok: "Senja",
    kakakKelompok: "Raelisa K",
    kakakPI: "Raelisa K",
  },
  {
    nama: "OVILIA SITOMPUL",
    fakultas: "FIS",
    noKel: "36",
    namaKelompok: "Dahlia",
    kakakKelompok: "Farel Arnando",
    kakakPI: "Farel Arnando",
  },
  {
    nama: "MOSES ANDREAN SYEBA",
    fakultas: "FEB",
    noKel: "36",
    namaKelompok: "Dahlia",
    kakakKelompok: "Farel Arnando",
    kakakPI: "Farel Arnando",
  },
  {
    nama: "YOHANNA MARIANY TAMPUBOLON",
    fakultas: "FEB",
    noKel: "36",
    namaKelompok: "Dahlia",
    kakakKelompok: "Farel Arnando",
    kakakPI: "Farel Arnando",
  },
  {
    nama: "SHINTA VALLERY DIVADILLONE TANNESA SIHOMBING",
    fakultas: "FMIPA",
    noKel: "36",
    namaKelompok: "Dahlia",
    kakakKelompok: "Farel Arnando",
    kakakPI: "Farel Arnando",
  },
  {
    nama: "JONATHAN SHALLOM CELLOSE",
    fakultas: "FMIPA",
    noKel: "36",
    namaKelompok: "Dahlia",
    kakakKelompok: "Farel Arnando",
    kakakPI: "Farel Arnando",
  },
  {
    nama: "JOSEPIN SIAHAAN",
    fakultas: "FV",
    noKel: "36",
    namaKelompok: "Dahlia",
    kakakKelompok: "Farel Arnando",
    kakakPI: "Farel Arnando",
  },
  {
    nama: "HARYO SEKTI PAMBUDI",
    fakultas: "FS",
    noKel: "36",
    namaKelompok: "Dahlia",
    kakakKelompok: "Farel Arnando",
    kakakPI: "Farel Arnando",
  },
  {
    nama: "NATHANIEL RUBY",
    fakultas: "FIK",
    noKel: "36",
    namaKelompok: "Dahlia",
    kakakKelompok: "Farel Arnando",
    kakakPI: "Farel Arnando",
  },
  {
    nama: "MARKUS ADI HERMANTO",
    fakultas: "FT",
    noKel: "36",
    namaKelompok: "Dahlia",
    kakakKelompok: "Farel Arnando",
    kakakPI: "Farel Arnando",
  },
  {
    nama: "LIONTIN SAULINA GLORIA ANASTASIA MANULLANG",
    fakultas: "FIP",
    noKel: "36",
    namaKelompok: "Dahlia",
    kakakKelompok: "Farel Arnando",
    kakakPI: "Farel Arnando",
  },
  {
    nama: "YOHANA TIUR MAIDA SIANIPAR",
    fakultas: "FT",
    noKel: "36",
    namaKelompok: "Dahlia",
    kakakKelompok: "Farel Arnando",
    kakakPI: "Farel Arnando",
  },
  {
    nama: "NEYFAZELLYNE PELANGI GRACE CHALYSTHA WINDY",
    fakultas: "FIS",
    noKel: "37",
    namaKelompok: "Angsa",
    kakakKelompok: "Stepy A",
    kakakPI: "Stepy A",
  },
  {
    nama: "YRENE JOITO TAMBA",
    fakultas: "FEB",
    noKel: "37",
    namaKelompok: "Angsa",
    kakakKelompok: "Stepy A",
    kakakPI: "Stepy A",
  },
  {
    nama: "SHELLY APRILIA",
    fakultas: "FMIPA",
    noKel: "37",
    namaKelompok: "Angsa",
    kakakKelompok: "Stepy A",
    kakakPI: "Stepy A",
  },
  {
    nama: "KEVIN JEREMY HASIBUAN",
    fakultas: "FMIPA",
    noKel: "37",
    namaKelompok: "Angsa",
    kakakKelompok: "Stepy A",
    kakakPI: "Stepy A",
  },
  {
    nama: "JOSHUA ORVIN",
    fakultas: "FV",
    noKel: "37",
    namaKelompok: "Angsa",
    kakakKelompok: "Stepy A",
    kakakPI: "Stepy A",
  },
  {
    nama: "JOCELIN CRYSTIAN WIRATAMA",
    fakultas: "FS",
    noKel: "37",
    namaKelompok: "Angsa",
    kakakKelompok: "Stepy A",
    kakakPI: "Stepy A",
  },
  {
    nama: "GREVITA ULITA BATUBARA",
    fakultas: "FIK",
    noKel: "37",
    namaKelompok: "Angsa",
    kakakKelompok: "Stepy A",
    kakakPI: "Stepy A",
  },
  {
    nama: "MATTHEW FARRELL ABRAHAM WIJAYA",
    fakultas: "FT",
    noKel: "37",
    namaKelompok: "Angsa",
    kakakKelompok: "Stepy A",
    kakakPI: "Stepy A",
  },
  {
    nama: "KEZYA RAHEL SARAGIH",
    fakultas: "FIP",
    noKel: "37",
    namaKelompok: "Angsa",
    kakakKelompok: "Stepy A",
    kakakPI: "Stepy A",
  },
  {
    nama: "VERONICA FALENCIA",
    fakultas: "FT",
    noKel: "37",
    namaKelompok: "Angsa",
    kakakKelompok: "Stepy A",
    kakakPI: "Stepy A",
  },
  {
    nama: "MODESTA PRIMA MANURUNG",
    fakultas: "FT",
    noKel: "37",
    namaKelompok: "Angsa",
    kakakKelompok: "Stepy A",
    kakakPI: "Stepy A",
  },
  {
    nama: "NATHANIA WANDA REZA",
    fakultas: "FIS",
    noKel: "38",
    namaKelompok: "Bangau",
    kakakKelompok: "Immanuel Rey",
    kakakPI: "Immanuel Rey",
  },
  {
    nama: "ISABELLE CHERRY SUNDAY",
    fakultas: "FEB",
    noKel: "38",
    namaKelompok: "Bangau",
    kakakKelompok: "Immanuel Rey",
    kakakPI: "Immanuel Rey",
  },
  {
    nama: "STELLA KIARA SHEELANA TRIXIE",
    fakultas: "FEB",
    noKel: "38",
    namaKelompok: "Bangau",
    kakakKelompok: "Immanuel Rey",
    kakakPI: "Immanuel Rey",
  },
  {
    nama: "SESILIA ARMEGI PUTRI",
    fakultas: "FMIPA",
    noKel: "38",
    namaKelompok: "Bangau",
    kakakKelompok: "Immanuel Rey",
    kakakPI: "Immanuel Rey",
  },
  {
    nama: "MARIO RAPHAEL C E SITEPU",
    fakultas: "FMIPA",
    noKel: "38",
    namaKelompok: "Bangau",
    kakakKelompok: "Immanuel Rey",
    kakakPI: "Immanuel Rey",
  },
  {
    nama: "LAMBANG PUTRA PAMUNGKAS",
    fakultas: "FV",
    noKel: "38",
    namaKelompok: "Bangau",
    kakakKelompok: "Immanuel Rey",
    kakakPI: "Immanuel Rey",
  },
  {
    nama: "ALFREDA VICKY PRIMA WIJAYA",
    fakultas: "FIK",
    noKel: "38",
    namaKelompok: "Bangau",
    kakakKelompok: "Immanuel Rey",
    kakakPI: "Immanuel Rey",
  },
  {
    nama: "FLOWRENNA ELVEN CANDRA WINATA",
    fakultas: "FS",
    noKel: "38",
    namaKelompok: "Bangau",
    kakakKelompok: "Immanuel Rey",
    kakakPI: "Immanuel Rey",
  },
  {
    nama: "MEY EVA WATI TAMBUN",
    fakultas: "FT",
    noKel: "38",
    namaKelompok: "Bangau",
    kakakKelompok: "Immanuel Rey",
    kakakPI: "Immanuel Rey",
  },
  {
    nama: "KESYA CATUR PUTRI",
    fakultas: "FIP",
    noKel: "38",
    namaKelompok: "Bangau",
    kakakKelompok: "Immanuel Rey",
    kakakPI: "Immanuel Rey",
  },
  {
    nama: "STEVIE SALOMO TITALEY",
    fakultas: "FT",
    noKel: "38",
    namaKelompok: "Bangau",
    kakakKelompok: "Immanuel Rey",
    kakakPI: "Immanuel Rey",
  },
  {
    nama: "MEYLANI MEGA SAPUTRI",
    fakultas: "FIS",
    noKel: "39",
    namaKelompok: "Labu",
    kakakKelompok: "Filadelfia A",
    kakakPI: "Filadelfia A",
  },
  {
    nama: "SHEREN YUEYINTA JOCELYN GWENDOLYN ATHALEE",
    fakultas: "FEB",
    noKel: "39",
    namaKelompok: "Labu",
    kakakKelompok: "Filadelfia A",
    kakakPI: "Filadelfia A",
  },
  {
    nama: "SELVIA SIHALOHO",
    fakultas: "FMIPA",
    noKel: "39",
    namaKelompok: "Labu",
    kakakKelompok: "Filadelfia A",
    kakakPI: "Filadelfia A",
  },
  {
    nama: "CHRISTINE PUTRI ARYWISNU",
    fakultas: "FK",
    noKel: "39",
    namaKelompok: "Labu",
    kakakKelompok: "Filadelfia A",
    kakakPI: "Filadelfia A",
  },
  {
    nama: "MIKHAELO CHRISTOPER BENECDIASTHA",
    fakultas: "FMIPA",
    noKel: "39",
    namaKelompok: "Labu",
    kakakKelompok: "Filadelfia A",
    kakakPI: "Filadelfia A",
  },
  {
    nama: "MARGARETHA ANGELINA NAINGGOLAN",
    fakultas: "FV",
    noKel: "39",
    namaKelompok: "Labu",
    kakakKelompok: "Filadelfia A",
    kakakPI: "Filadelfia A",
  },
  {
    nama: "KEISYA AURELIE FAZA",
    fakultas: "FIK",
    noKel: "39",
    namaKelompok: "Labu",
    kakakKelompok: "Filadelfia A",
    kakakPI: "Filadelfia A",
  },
  {
    nama: "BRIANI ABIGAIL AWORYANE",
    fakultas: "FS",
    noKel: "39",
    namaKelompok: "Labu",
    kakakKelompok: "Filadelfia A",
    kakakPI: "Filadelfia A",
  },
  {
    nama: "MICHELLE ANGELIQUE CARANAY SOEMARIYO",
    fakultas: "FT",
    noKel: "39",
    namaKelompok: "Labu",
    kakakKelompok: "Filadelfia A",
    kakakPI: "Filadelfia A",
  },
  {
    nama: "KASIH SOLA FIDE",
    fakultas: "FIP",
    noKel: "39",
    namaKelompok: "Labu",
    kakakKelompok: "Filadelfia A",
    kakakPI: "Filadelfia A",
  },
  {
    nama: "JUANITA MARGERY RAHAYU",
    fakultas: "FIP",
    noKel: "39",
    namaKelompok: "Labu",
    kakakKelompok: "Filadelfia A",
    kakakPI: "Filadelfia A",
  },
  {
    nama: "JESSICA NOVELIA ASRAKA",
    fakultas: "FIS",
    noKel: "40",
    namaKelompok: "Apel",
    kakakKelompok: "Lamtama M",
    kakakPI: "Lamtama M",
  },
  {
    nama: "RUTH KERIAHENTA BR BARUS",
    fakultas: "FMIPA",
    noKel: "40",
    namaKelompok: "Apel",
    kakakKelompok: "Lamtama M",
    kakakPI: "Lamtama M",
  },
  {
    nama: "MARTA YUANITA",
    fakultas: "",
    noKel: "40",
    namaKelompok: "Apel",
    kakakKelompok: "Lamtama M",
    kakakPI: "Lamtama M",
  },
  {
    nama: "DAVID TRISTAN NASMORO",
    fakultas: "FEB",
    noKel: "40",
    namaKelompok: "Apel",
    kakakKelompok: "Lamtama M",
    kakakPI: "Lamtama M",
  },
  {
    nama: "MARTA YUANITA",
    fakultas: "FEB",
    noKel: "40",
    namaKelompok: "Apel",
    kakakKelompok: "Lamtama M",
    kakakPI: "Lamtama M",
  },
  {
    nama: "ANDREA ANGELINA TELAUMBANUA",
    fakultas: "FK",
    noKel: "40",
    namaKelompok: "Apel",
    kakakKelompok: "Lamtama M",
    kakakPI: "Lamtama M",
  },
  {
    nama: "NIMROD KRISTIANO SIHOMBING",
    fakultas: "FMIPA",
    noKel: "40",
    namaKelompok: "Apel",
    kakakKelompok: "Lamtama M",
    kakakPI: "Lamtama M",
  },
  {
    nama: "NATALIA MEYLAN LOBANG",
    fakultas: "FV",
    noKel: "40",
    namaKelompok: "Apel",
    kakakKelompok: "Lamtama M",
    kakakPI: "Lamtama M",
  },
  {
    nama: "ANASTASIA TIRZAH ARDIYANTO",
    fakultas: "FIK",
    noKel: "40",
    namaKelompok: "Apel",
    kakakKelompok: "Lamtama M",
    kakakPI: "Lamtama M",
  },
  {
    nama: "JEWEL LINDSAY DONI",
    fakultas: "FS",
    noKel: "40",
    namaKelompok: "Apel",
    kakakKelompok: "Lamtama M",
    kakakPI: "Lamtama M",
  },
  {
    nama: "MIKE DOUGLAS SIMANGUNSONG",
    fakultas: "FT",
    noKel: "40",
    namaKelompok: "Apel",
    kakakKelompok: "Lamtama M",
    kakakPI: "Lamtama M",
  },
  {
    nama: "JOSUA EKA PUTRA EMANUEL",
    fakultas: "FIS",
    noKel: "41",
    namaKelompok: "Anggur",
    kakakKelompok: "Ira",
    kakakPI: "Apvia",
  },
  {
    nama: "DESMITHA GRECYA MARGARET BR SIRINGO-RINGO",
    fakultas: "FIS",
    noKel: "41",
    namaKelompok: "Anggur",
    kakakKelompok: "Ira",
    kakakPI: "Apvia",
  },
  {
    nama: "RUTH DEANDRA OLIVE HINDARIADI",
    fakultas: "FPSI",
    noKel: "41",
    namaKelompok: "Anggur",
    kakakKelompok: "Ira",
    kakakPI: "Apvia",
  },
  {
    nama: "RICKI RONAL MAAS",
    fakultas: "FEB",
    noKel: "41",
    namaKelompok: "Anggur",
    kakakKelompok: "Ira",
    kakakPI: "Apvia",
  },
  {
    nama: "IVY IVANA YAKUB",
    fakultas: "FEB",
    noKel: "41",
    namaKelompok: "Anggur",
    kakakKelompok: "Ira",
    kakakPI: "Apvia",
  },
  {
    nama: "VALEN NIEL KUSMIRA ZEGA",
    fakultas: "FMIPA",
    noKel: "41",
    namaKelompok: "Anggur",
    kakakKelompok: "Ira",
    kakakPI: "Apvia",
  },
  {
    nama: "GRACELL HOLLYA KURNIAWAN",
    fakultas: "FS",
    noKel: "41",
    namaKelompok: "Anggur",
    kakakKelompok: "Ira",
    kakakPI: "Apvia",
  },
  {
    nama: "GALVIN RENARDO LAYANG",
    fakultas: "FMIPA",
    noKel: "41",
    namaKelompok: "Anggur",
    kakakKelompok: "Ira",
    kakakPI: "Apvia",
  },
  {
    nama: "NI KOMANG VIOLA SEPTANIA ADELINE",
    fakultas: "FV",
    noKel: "41",
    namaKelompok: "Anggur",
    kakakKelompok: "Ira",
    kakakPI: "Apvia",
  },
  {
    nama: "REIVANIO IMMANUEL ETANIM",
    fakultas: "FIK",
    noKel: "41",
    namaKelompok: "Anggur",
    kakakKelompok: "Ira",
    kakakPI: "Apvia",
  },
  {
    nama: "PRISKA ROSALINA POPPY OLUA",
    fakultas: "FS",
    noKel: "41",
    namaKelompok: "Anggur",
    kakakKelompok: "Ira",
    kakakPI: "Apvia",
  },
  {
    nama: "KEVIN VOLCKER HUTAJULU",
    fakultas: "FIS",
    noKel: "42",
    namaKelompok: "Gandum",
    kakakKelompok: "Arni A",
    kakakPI: "Arni A",
  },
  {
    nama: "FRANSISKA HAMIDA PRATAMA SINAGA",
    fakultas: "FIS",
    noKel: "42",
    namaKelompok: "Gandum",
    kakakKelompok: "Arni A",
    kakakPI: "Arni A",
  },
  {
    nama: "DAVID CHRISTOPHER",
    fakultas: "FPSI",
    noKel: "42",
    namaKelompok: "Gandum",
    kakakKelompok: "Arni A",
    kakakPI: "Arni A",
  },
  {
    nama: "UBAT CRISTIAN SIAGIAN",
    fakultas: "FEB",
    noKel: "42",
    namaKelompok: "Gandum",
    kakakKelompok: "Arni A",
    kakakPI: "Arni A",
  },
  {
    nama: "STEVANI GARNETA SITORUS",
    fakultas: "FEB",
    noKel: "42",
    namaKelompok: "Gandum",
    kakakKelompok: "Arni A",
    kakakPI: "Arni A",
  },
  {
    nama: "YESICHA STEFANIA",
    fakultas: "FMIPA",
    noKel: "42",
    namaKelompok: "Gandum",
    kakakKelompok: "Arni A",
    kakakPI: "Arni A",
  },
  {
    nama: "FRENDI SIPAYUNG",
    fakultas: "FMIPA",
    noKel: "42",
    namaKelompok: "Gandum",
    kakakKelompok: "Arni A",
    kakakPI: "Arni A",
  },
  {
    nama: "NARLI NONINA MESE",
    fakultas: "FS",
    noKel: "42",
    namaKelompok: "Gandum",
    kakakKelompok: "Arni A",
    kakakPI: "Arni A",
  },
  {
    nama: "OLLYA QUEENISHA HUTABARAT",
    fakultas: "FV",
    noKel: "42",
    namaKelompok: "Gandum",
    kakakKelompok: "Arni A",
    kakakPI: "Arni A",
  },
  {
    nama: "KEZYA AURRELIA SIAGIAN",
    fakultas: "FIK",
    noKel: "42",
    namaKelompok: "Gandum",
    kakakKelompok: "Arni A",
    kakakPI: "Arni A",
  },
  {
    nama: "LESTARI KHEINT FEBRIYANTI SIMANJUNTAK",
    fakultas: "FS",
    noKel: "42",
    namaKelompok: "Gandum",
    kakakKelompok: "Arni A",
    kakakPI: "Arni A",
  },
  {
    nama: "LEO FADLI SAPUTRA",
    fakultas: "FIS",
    noKel: "43",
    namaKelompok: "Delima",
    kakakKelompok: "Anabella A",
    kakakPI: "Anabella A",
  },
  {
    nama: "KAYLA CINTYA JOITO NAPITUPULU",
    fakultas: "FIS",
    noKel: "43",
    namaKelompok: "Delima",
    kakakKelompok: "",
    kakakPI: "Anabella A",
  },
  {
    nama: "SAMUEL CHRISTOPER IROTH",
    fakultas: "FPSI",
    noKel: "43",
    namaKelompok: "Delima",
    kakakKelompok: "Anabella A",
    kakakPI: "Anabella A",
  },
  {
    nama: "DARIUS AUREL BAGUS SATRIYA",
    fakultas: "FEB",
    noKel: "43",
    namaKelompok: "Delima",
    kakakKelompok: "Anabella A",
    kakakPI: "Anabella A",
  },
  {
    nama: "GABRIELA GLORY INSANIAN TEBISI",
    fakultas: "FEB",
    noKel: "43",
    namaKelompok: "Delima",
    kakakKelompok: "Anabella A",
    kakakPI: "Anabella A",
  },
  {
    nama: "GRACELA BR TAMBUNAN",
    fakultas: "FMIPA",
    noKel: "43",
    namaKelompok: "Delima",
    kakakKelompok: "Anabella A",
    kakakPI: "Anabella A",
  },
  {
    nama: "ELNATH TEGAR PRAWIRO YUDHO",
    fakultas: "FMIPA",
    noKel: "43",
    namaKelompok: "Delima",
    kakakKelompok: "Anabella A",
    kakakPI: "Anabella A",
  },
  {
    nama: "METANOIA XHEZYA GUNAWAN",
    fakultas: "FS",
    noKel: "43",
    namaKelompok: "Delima",
    kakakKelompok: "Anabella A",
    kakakPI: "Anabella A",
  },
  {
    nama: "PUTRI LASMA ADHYWIDI SINAGA",
    fakultas: "FV",
    noKel: "43",
    namaKelompok: "Delima",
    kakakKelompok: "Anabella A",
    kakakPI: "Anabella A",
  },
  {
    nama: "GRACELLA KRISTIARUMAY WARDONO",
    fakultas: "FIK",
    noKel: "43",
    namaKelompok: "Delima",
    kakakKelompok: "Anabella A",
    kakakPI: "Anabella A",
  },
  {
    nama: "PRATISTHA ARDYANA KRISTIAN",
    fakultas: "FS",
    noKel: "43",
    namaKelompok: "Delima",
    kakakKelompok: "Anabella A",
    kakakPI: "Anabella A",
  },
  {
    nama: "REMIMA AGRESIA CIOLITA GINTING",
    fakultas: "FIS",
    noKel: "44",
    namaKelompok: "Rembulan",
    kakakKelompok: "Airell",
    kakakPI: "Maureen K",
  },
  {
    nama: "VEBRY ANISA SINAGA",
    fakultas: "FIS",
    noKel: "44",
    namaKelompok: "Rembulan",
    kakakKelompok: "Airell",
    kakakPI: "Maureen K",
  },
  {
    nama: "THITO ABRAHAM OCTAVIANUS HASOLOAN SIDABUTAR",
    fakultas: "FEB",
    noKel: "44",
    namaKelompok: "Rembulan",
    kakakKelompok: "Airell",
    kakakPI: "Maureen K",
  },
  {
    nama: "VELLICIA SHERREN HARTONO",
    fakultas: "FEB",
    noKel: "44",
    namaKelompok: "Rembulan",
    kakakKelompok: "Airell",
    kakakPI: "Maureen K",
  },
  {
    nama: "NEILAH HARYANI ZEGA",
    fakultas: "FMIPA",
    noKel: "44",
    namaKelompok: "Rembulan",
    kakakKelompok: "Airell",
    kakakPI: "Maureen K",
  },
  {
    nama: "CHRISNA WAHYU HUSADA",
    fakultas: "FMIPA",
    noKel: "44",
    namaKelompok: "Rembulan",
    kakakKelompok: "Airell",
    kakakPI: "Maureen K",
  },
  {
    nama: "JOYCELINE KURNIAWAN",
    fakultas: "FS",
    noKel: "44",
    namaKelompok: "Rembulan",
    kakakKelompok: "Airell",
    kakakPI: "Maureen K",
  },
  {
    nama: "RESNA ULIEKLESIA SIAGIAN",
    fakultas: "FV",
    noKel: "44",
    namaKelompok: "Rembulan",
    kakakKelompok: "Airell",
    kakakPI: "Maureen K",
  },
  {
    nama: "BUNGA ENGGELINA NAINGGOLAN LUMBANRAJA",
    fakultas: "FIK",
    noKel: "44",
    namaKelompok: "Rembulan",
    kakakKelompok: "Airell",
    kakakPI: "Maureen K",
  },
  {
    nama: "MUNCARSIH SRIYATI WIDYA SETYANINGSIH",
    fakultas: "FS",
    noKel: "44",
    namaKelompok: "Rembulan",
    kakakKelompok: "Airell",
    kakakPI: "Maureen K",
  },
  {
    nama: "NATHANIA ANDREA CHRISTINE",
    fakultas: "FT",
    noKel: "44",
    namaKelompok: "Rembulan",
    kakakKelompok: "Airell",
    kakakPI: "Maureen K",
  },
  {
    nama: "RIBKA AMELIA PUTRI ADIKARSA",
    fakultas: "FIS",
    noKel: "45",
    namaKelompok: "Kapibara",
    kakakKelompok: "Theo",
    kakakPI: "Ellasya M",
  },
  {
    nama: "RIBKA FERIANI",
    fakultas: "FIS",
    noKel: "45",
    namaKelompok: "Kapibara",
    kakakKelompok: "Theo",
    kakakPI: "Ellasya M",
  },
  {
    nama: "ALLAN DWIKA NOVIADI",
    fakultas: "FEB",
    noKel: "45",
    namaKelompok: "Kapibara",
    kakakKelompok: "Theo",
    kakakPI: "Ellasya M",
  },
  {
    nama: "CERIA REKA JULITA SIMANJUNTAK",
    fakultas: "FEB",
    noKel: "45",
    namaKelompok: "Kapibara",
    kakakKelompok: "Theo",
    kakakPI: "Ellasya M",
  },
  {
    nama: "BRYANT PRAWIRANTA PERANGIN ANGIN",
    fakultas: "FMIPA",
    noKel: "45",
    namaKelompok: "Kapibara",
    kakakKelompok: "Theo",
    kakakPI: "Ellasya M",
  },
  {
    nama: "REYANALDI SAPUTRA SIANTURI",
    fakultas: "FV",
    noKel: "45",
    namaKelompok: "Kapibara",
    kakakKelompok: "Theo",
    kakakPI: "Ellasya M",
  },
  {
    nama: "FRANKLYN IMANUEL",
    fakultas: "FS",
    noKel: "45",
    namaKelompok: "Kapibara",
    kakakKelompok: "Theo",
    kakakPI: "Ellasya M",
  },
  {
    nama: "YOHANA GRACIA SEPTYANTI",
    fakultas: "FIK",
    noKel: "45",
    namaKelompok: "Kapibara",
    kakakKelompok: "Theo",
    kakakPI: "Ellasya M",
  },
  {
    nama: "PIERCE EXCHAUDIO PURBA",
    fakultas: "FT",
    noKel: "45",
    namaKelompok: "Kapibara",
    kakakKelompok: "Theo",
    kakakPI: "Ellasya M",
  },
  {
    nama: "SMYRNA LOKANANTA PERTIWI SPIZBART STEPHANUS",
    fakultas: "FT",
    noKel: "45",
    namaKelompok: "Kapibara",
    kakakKelompok: "Theo",
    kakakPI: "Ellasya M",
  },
  {
    nama: "TABITA MELANI NATHANIA",
    fakultas: "FIP",
    noKel: "45",
    namaKelompok: "Kapibara",
    kakakKelompok: "Theo",
    kakakPI: "Ellasya M",
  },
];

export default kelompokMaba;
